/*************************************
This program can be used to evaluate a jboost-trained classifier on new data.  
The code contains a single procedure:

  double car_predict(void **attr, double *ret)

The first argument attr is an array of pointers corresponding to the
attributes specified in the spec file.  Thus, if attribute i is text,
then attr[i] must be a char array; if attribute i is a number, then
*attr[i] must be a double; and if attribute i is finite, then *attr[i]
must be an int containing the index of the chosen value.  An undefined
attribute is indicated by setting attr[i] to NULL.

Specifically, these pointers are:

     index    attr.type    data.type   name
   ------------------------------------------
        0     number       double      H
        1     number       double      S
        2     number       double      V

The second argument ret is a pointer to an array of k doubles, where k
is the number of classes.  The scores for each of the k classes will
be stored in this array.  If ret is NULL, then no scores are stored.
In any case, predict returns the score for class 0 (=ret[0]).

These scores correspond to the classes as follows:

            index       class name
           ------------------------
               0        0
               1        1

This classifier was automatically generated by jboost on
Wed May 26 00:50:39 PDT 2010.
*************************************/
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <limits.h>
#include <float.h>


typedef double Prediction_t;
#define reset_pred()  {p = 0.0;}
#define add_pred(X) {p += (X);}
#define finalize_pred()  ((r) ? (r[1] = p , r[0] = -p) : -p)
#define defined_attr(X)  (attr[X])
#define int_attr(X)      (*((int *) attr[X]))
#define attr_contains_token(X,Y) (tokens[X][Y])
#define double_attr(X)   (*((double *) attr[X]))

#define WHITE_CHARS   " \t\n"
typedef struct hash_table_entry_s {
  char *key;
  int id;
  struct hash_table_entry_s *next;
} HashTableEntry_t;
static char *keys[] = {
};
#define num_keys  (0)
static HashTableEntry_t **hash_table = NULL;
#define hash_table_size  (1031)
static char *tokens[1];
static int text_attr[] = {};
#define num_text_attr  (0)
static char **text_patterns[] = {
};

static char **words;
static int num_words;
static int cur_word;
static char *pattern;
static int pattern_len;

static void set_pattern(int n, char **m_w, char *pat) {
  words = m_w;
  pattern = pat;
  cur_word = 0;
  num_words = n;
  pattern_len = strlen(pat);
}

#define more_tokens()  (cur_word <= num_words - pattern_len)

#define ADD_CHAR(S)  { \
  if (c >= buffer_size) { \
    buffer_size = 2 * buffer_size + 1; \
    buffer = (char *) realloc(buffer, buffer_size * sizeof(char)); \
  } \
  buffer[c++] = (S); \
}

static char *next_token(void) {
  static char *buffer = NULL;
  static int buffer_size = 0;
  int i, c;
  char *s;

  c = 0;
  for (s = pattern; *s; s++)
    ADD_CHAR(*s);

  for (i = 0; i < pattern_len; i++) {
    if (pattern[i] == '1') {
      ADD_CHAR(' ');
      for (s = words[cur_word + i]; *s; s++)
	ADD_CHAR(*s);
    }
  }
  ADD_CHAR('\0');
  cur_word++;
  return buffer;
}

static int
hash(char *s) {
  static int *coef = NULL;
  static int max_len = 0;
  int len = strlen(s);
  int i, h;

  if (len > max_len) {
    i = max_len;
    max_len = 2 * len;
    coef = (int *) realloc(coef, max_len * sizeof(int));
    for (; i < max_len; i++)
      coef[i] = random() % hash_table_size;
  }

  h = 0;
  for (i = 0; i < len; i++) {
     if (h >= INT_MAX - (hash_table_size - 1) * 255)
       h = h % hash_table_size;
     h += coef[i] * s[i];
  }
  return (h % hash_table_size);
}

double car_predict(void **attr, double *r) {
  int i, j, h, a;
  HashTableEntry_t *entry;
  char *s;
  static char **words = NULL;
  static int max_word_list_size = 0;
  int num_words;
  static char *buffer = NULL;
  static int buffer_size = 0;
  char **pat;

  Prediction_t p;

  if (!hash_table) {
    hash_table = (HashTableEntry_t **)
      malloc(hash_table_size * sizeof(HashTableEntry_t *));
    for (i = 0; i < hash_table_size; i++)
      hash_table[i] = NULL;
    for (i = 0; i < num_keys; i++) {
      h = hash(keys[i]);
      entry = (HashTableEntry_t *) malloc(sizeof(HashTableEntry_t));
      entry->key = keys[i];
      entry->id = i;
      entry->next = hash_table[h];
      hash_table[h] = entry;
    }
    for (i = 0; i < num_text_attr; i++)
      tokens[text_attr[i]] = (char *) malloc(num_keys * sizeof(char));
  }

  for (i = 0; i < num_text_attr; i++) {
    a = text_attr[i];
    if (!defined_attr(a))
      continue;
    for (j = 0; j < num_keys; j++)
      tokens[a][j] = 0;

    while (strlcpy(buffer, attr[a], buffer_size) >= buffer_size) {
      buffer_size = 2 * strlen(attr[a]);
      buffer = (char *) realloc(buffer, (buffer_size+1) * sizeof(char));
    }
    num_words = 0;
    for (s = strtok(buffer, WHITE_CHARS); s; s = strtok(NULL, WHITE_CHARS)) {
      if (num_words >= max_word_list_size) {
        max_word_list_size = 2 * max_word_list_size + 1;
        words = (char **) realloc(words, max_word_list_size * sizeof(char *));
      }
      words[num_words++] = s;
    }
    for (pat = text_patterns[i]; *pat; pat++) {
      set_pattern(num_words, words, *pat);
      while (more_tokens()) {
        s = next_token();
        for (entry = hash_table[hash(s)]; entry; entry = entry->next)
          if (!strcmp(entry->key, s)) {
            tokens[a][entry->id] = 1;
            break;
          }
        }
      }
  }

  reset_pred();

  add_pred(   /* R */
             -0.36511298602576925);
  if (defined_attr(0)) {  /* R.0 */
    if (double_attr(0) <= 0.20500000000000002) {
      add_pred(   /* R.0:0 */
                 -0.8775327271367709);
      if (defined_attr(2)) {  /* R.0:0.0 */
        if (double_attr(2) <= 0.605) {
          add_pred(   /* R.0:0.0:0 */
                     -0.47828252249084635);
          if (defined_attr(2)) {  /* R.0:0.0:0.0 */
            if (double_attr(2) <= 0.505) {
              add_pred(   /* R.0:0.0:0.0:0 */
                         0.6222500095766186);
              if (defined_attr(2)) {  /* R.0:0.0:0.0:0.0 */
                if (double_attr(2) <= 0.0050) {
                  add_pred(   /* R.0:0.0:0.0:0.0:0 */
                             -2.495945062993322);
                  if (defined_attr(0)) {  /* R.0:0.0:0.0:0.0:0.0 */
                    if (double_attr(0) <= 0.085) {
                      add_pred(   /* R.0:0.0:0.0:0.0:0.0:0 */
                                 -0.09705335225867971);
                    } else {
                      add_pred(   /* R.0:0.0:0.0:0.0:0.0:1 */
                                 1.714105887925911);
                    }
                  }
                } else {
                  add_pred(   /* R.0:0.0:0.0:0.0:1 */
                             0.6411232180857883);
                  if (defined_attr(2)) {  /* R.0:0.0:0.0:0.0:1.0 */
                    if (double_attr(2) <= 0.46499999999999997) {
                      add_pred(   /* R.0:0.0:0.0:0.0:1.0:0 */
                                 0.2812675507363056);
                      if (defined_attr(2)) {  /* R.0:0.0:0.0:0.0:1.0:0.0 */
                        if (double_attr(2) <= 0.025) {
                          add_pred(   /* R.0:0.0:0.0:0.0:1.0:0.0:0 */
                                     -1.464367231838748);
                        } else {
                          add_pred(   /* R.0:0.0:0.0:0.0:1.0:0.0:1 */
                                     0.06129821922981282);
                          if (defined_attr(2)) {  /* R.0:0.0:0.0:0.0:1.0:0.0:1.0 */
                            if (double_attr(2) <= 0.385) {
                              add_pred(   /* R.0:0.0:0.0:0.0:1.0:0.0:1.0:0 */
                                         0.06260666339684677);
                            } else {
                              add_pred(   /* R.0:0.0:0.0:0.0:1.0:0.0:1.0:1 */
                                         -0.18581962864136106);
                            }
                          }
                        }
                      }
                    } else {
                      add_pred(   /* R.0:0.0:0.0:0.0:1.0:1 */
                                 -0.4737989572679341);
                      if (defined_attr(2)) {  /* R.0:0.0:0.0:0.0:1.0:1.0 */
                        if (double_attr(2) <= 0.495) {
                          add_pred(   /* R.0:0.0:0.0:0.0:1.0:1.0:0 */
                                     0.20853011882157407);
                        } else {
                          add_pred(   /* R.0:0.0:0.0:0.0:1.0:1.0:1 */
                                     -0.2281060418623059);
                        }
                      }
                    }
                  }
                }
              }
              if (defined_attr(1)) {  /* R.0:0.0:0.0:0.1 */
                if (double_attr(1) <= 0.095) {
                  add_pred(   /* R.0:0.0:0.0:0.1:0 */
                             -0.09679165006177287);
                } else {
                  add_pred(   /* R.0:0.0:0.0:0.1:1 */
                             0.2647813317495866);
                  if (defined_attr(0)) {  /* R.0:0.0:0.0:0.1:1.0 */
                    if (double_attr(0) <= 0.065) {
                      add_pred(   /* R.0:0.0:0.0:0.1:1.0:0 */
                                 0.2301671584501343);
                    } else {
                      add_pred(   /* R.0:0.0:0.0:0.1:1.0:1 */
                                 -0.19223558617969044);
                    }
                  }
                }
              }
            } else {
              add_pred(   /* R.0:0.0:0.0:1 */
                         -0.45596491643426174);
              if (defined_attr(1)) {  /* R.0:0.0:0.0:1.0 */
                if (double_attr(1) <= 0.045) {
                  add_pred(   /* R.0:0.0:0.0:1.0:0 */
                             1.0116414752167597);
                  if (defined_attr(1)) {  /* R.0:0.0:0.0:1.0:0.0 */
                    if (double_attr(1) <= 0.035) {
                      add_pred(   /* R.0:0.0:0.0:1.0:0.0:0 */
                                 0.3174563624811186);
                      if (defined_attr(1)) {  /* R.0:0.0:0.0:1.0:0.0:0.0 */
                        if (double_attr(1) <= 0.015) {
                          add_pred(   /* R.0:0.0:0.0:1.0:0.0:0.0:0 */
                                     0.1891866608363273);
                        } else {
                          add_pred(   /* R.0:0.0:0.0:1.0:0.0:0.0:1 */
                                     -0.17295364750663464);
                        }
                      }
                    } else {
                      add_pred(   /* R.0:0.0:0.0:1.0:0.0:1 */
                                 -0.4010352616782994);
                    }
                  }
                  if (defined_attr(2)) {  /* R.0:0.0:0.0:1.0:0.1 */
                    if (double_attr(2) <= 0.535) {
                      add_pred(   /* R.0:0.0:0.0:1.0:0.1:0 */
                                 -0.16647915741515917);
                    } else {
                      add_pred(   /* R.0:0.0:0.0:1.0:0.1:1 */
                                 0.1582138486067862);
                    }
                  }
                } else {
                  add_pred(   /* R.0:0.0:0.0:1.0:1 */
                             -0.254538484948837);
                  if (defined_attr(0)) {  /* R.0:0.0:0.0:1.0:1.0 */
                    if (double_attr(0) <= 0.065) {
                      add_pred(   /* R.0:0.0:0.0:1.0:1.0:0 */
                                 1.1519538394459747);
                      if (defined_attr(0)) {  /* R.0:0.0:0.0:1.0:1.0:0.0 */
                        if (double_attr(0) <= 0.045) {
                          add_pred(   /* R.0:0.0:0.0:1.0:1.0:0.0:0 */
                                     0.029545059318841185);
                        } else {
                          add_pred(   /* R.0:0.0:0.0:1.0:1.0:0.0:1 */
                                     -0.35126993278287993);
                        }
                      }
                    } else {
                      add_pred(   /* R.0:0.0:0.0:1.0:1.0:1 */
                                 -0.11607232951567055);
                      if (defined_attr(0)) {  /* R.0:0.0:0.0:1.0:1.0:1.0 */
                        if (double_attr(0) <= 0.14500000000000002) {
                          add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.0:0 */
                                     -0.1275692731373044);
                        } else {
                          add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.0:1 */
                                     0.8314580015565833);
                        }
                      }
                      if (defined_attr(2)) {  /* R.0:0.0:0.0:1.0:1.0:1.1 */
                        if (double_attr(2) <= 0.585) {
                          add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0 */
                                     -0.05822863125042068);
                          if (defined_attr(1)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0 */
                            if (double_attr(1) <= 0.055) {
                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:0 */
                                         0.6025911374001279);
                            } else {
                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1 */
                                         -0.08593473406932514);
                              if (defined_attr(2)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0 */
                                if (double_attr(2) <= 0.515) {
                                  add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:0 */
                                             0.7236855917714768);
                                  if (defined_attr(1)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:0.0 */
                                    if (double_attr(1) <= 0.08499999999999999) {
                                      add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:0.0:0 */
                                                 -0.1271089852205909);
                                    } else {
                                      add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:0.0:1 */
                                                 0.5081684343668368);
                                    }
                                  }
                                } else {
                                  add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1 */
                                             -0.019600995078537065);
                                  if (defined_attr(0)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.0 */
                                    if (double_attr(0) <= 0.07500000000000001) {
                                      add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.0:0 */
                                                 0.7183342665614796);
                                    } else {
                                      add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.0:1 */
                                                 0.004273077511610335);
                                      if (defined_attr(0)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.0:1.0 */
                                        if (double_attr(0) <= 0.095) {
                                          add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.0:1.0:0 */
                                                     0.3654007965079635);
                                          if (defined_attr(2)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.0:1.0:0.0 */
                                            if (double_attr(2) <= 0.545) {
                                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.0:1.0:0.0:0 */
                                                         0.4115059411567737);
                                            } else {
                                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.0:1.0:0.0:1 */
                                                         0.04172416568735047);
                                            }
                                          }
                                        } else {
                                          add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.0:1.0:1 */
                                                     -0.05603585110590767);
                                        }
                                      }
                                    }
                                  }
                                  if (defined_attr(1)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1 */
                                    if (double_attr(1) <= 0.08499999999999999) {
                                      add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:0 */
                                                 0.18616562558107302);
                                      if (defined_attr(1)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:0.0 */
                                        if (double_attr(1) <= 0.07500000000000001) {
                                          add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:0.0:0 */
                                                     0.04375422071065759);
                                          if (defined_attr(2)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:0.0:0.0 */
                                            if (double_attr(2) <= 0.545) {
                                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:0.0:0.0:0 */
                                                         -0.13723870126609952);
                                            } else {
                                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:0.0:0.0:1 */
                                                         0.14096381329297655);
                                            }
                                          }
                                        } else {
                                          add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:0.0:1 */
                                                     -0.2298436730598754);
                                        }
                                      }
                                    } else {
                                      add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1 */
                                                 -0.13369557492608847);
                                      if (defined_attr(2)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0 */
                                        if (double_attr(2) <= 0.535) {
                                          add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:0 */
                                                     0.34067511217493013);
                                          if (defined_attr(0)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:0.0 */
                                            if (double_attr(0) <= 0.125) {
                                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:0.0:0 */
                                                         0.5265630076551792);
                                            } else {
                                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:0.0:1 */
                                                         -0.38709824664858233);
                                              if (defined_attr(1)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:0.0:1.0 */
                                                if (double_attr(1) <= 0.10500000000000001) {
                                                  add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:0.0:1.0:0 */
                                                             -0.054183755955601653);
                                                } else {
                                                  add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:0.0:1.0:1 */
                                                             0.6540153326326346);
                                                }
                                              }
                                            }
                                          }
                                          if (defined_attr(1)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:0.1 */
                                            if (double_attr(1) <= 0.095) {
                                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:0.1:0 */
                                                         -0.3855708288950502);
                                            } else {
                                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:0.1:1 */
                                                         0.36474826609453287);
                                            }
                                          }
                                        } else {
                                          add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1 */
                                                     -0.10749326465912067);
                                          if (defined_attr(1)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0 */
                                            if (double_attr(1) <= 0.14500000000000002) {
                                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0 */
                                                         0.009469729504029458);
                                              if (defined_attr(1)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0 */
                                                if (double_attr(1) <= 0.095) {
                                                  add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0:0 */
                                                             0.24690389084455575);
                                                } else {
                                                  add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0:1 */
                                                             -0.10839866635844475);
                                                  if (defined_attr(0)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0:1.0 */
                                                    if (double_attr(0) <= 0.08499999999999999) {
                                                      add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0:1.0:0 */
                                                                 -0.33163517043546625);
                                                      if (defined_attr(0)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0:1.0:0.0 */
                                                        if (double_attr(0) <= 0.07500000000000001) {
                                                          add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0:1.0:0.0:0 */
                                                                     0.5457509366395858);
                                                        } else {
                                                          add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0:1.0:0.0:1 */
                                                                     -0.48157682048943756);
                                                          if (defined_attr(2)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0:1.0:0.0:1.0 */
                                                            if (double_attr(2) <= 0.575) {
                                                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0:1.0:0.0:1.0:0 */
                                                                         -0.23300585077982672);
                                                            } else {
                                                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0:1.0:0.0:1.0:1 */
                                                                         -3.1087698049411543);
                                                            }
                                                          }
                                                        }
                                                      }
                                                    } else {
                                                      add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0:1.0:1 */
                                                                 0.08501050614792105);
                                                      if (defined_attr(1)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0:1.0:1.0 */
                                                        if (double_attr(1) <= 0.11499999999999999) {
                                                          add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0:1.0:1.0:0 */
                                                                     -0.13598666505754342);
                                                        } else {
                                                          add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0:1.0:1.0:1 */
                                                                     0.2790433872359414);
                                                          if (defined_attr(0)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0:1.0:1.0:1.0 */
                                                            if (double_attr(0) <= 0.10500000000000001) {
                                                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0:1.0:1.0:1.0:0 */
                                                                         -0.23577727142850188);
                                                            } else {
                                                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.0:1.0:1.0:1.0:1 */
                                                                         0.382065248578431);
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                              if (defined_attr(0)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.1 */
                                                if (double_attr(0) <= 0.125) {
                                                  add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.1:0 */
                                                             0.10654775593598);
                                                } else {
                                                  add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:0.1:1 */
                                                             -0.2203196721529899);
                                                }
                                              }
                                            } else {
                                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.0:1.0:1.1:1.0:1.0:1 */
                                                         0.732154988322857);
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                          if (defined_attr(2)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.1 */
                            if (double_attr(2) <= 0.565) {
                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.1:0 */
                                         -0.03990618596862078);
                            } else {
                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.1:1 */
                                         0.28763957052593553);
                              if (defined_attr(1)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:0.1:1.0 */
                                if (double_attr(1) <= 0.10500000000000001) {
                                  add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.1:1.0:0 */
                                             0.24062850641979766);
                                } else {
                                  add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:0.1:1.0:1 */
                                             -0.5864785076605149);
                                }
                              }
                            }
                          }
                        } else {
                          add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:1 */
                                     1.012327475018163);
                          if (defined_attr(1)) {  /* R.0:0.0:0.0:1.0:1.0:1.1:1.0 */
                            if (double_attr(1) <= 0.11499999999999999) {
                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:1.0:0 */
                                         0.228027972583556);
                            } else {
                              add_pred(   /* R.0:0.0:0.0:1.0:1.0:1.1:1.0:1 */
                                         -0.5369250276702505);
                            }
                          }
                        }
                      }
                    }
                  }
                  if (defined_attr(1)) {  /* R.0:0.0:0.0:1.0:1.1 */
                    if (double_attr(1) <= 0.135) {
                      add_pred(   /* R.0:0.0:0.0:1.0:1.1:0 */
                                 -0.05606757624504999);
                    } else {
                      add_pred(   /* R.0:0.0:0.0:1.0:1.1:1 */
                                 0.9006873663780077);
                    }
                  }
                }
              }
            }
          }
        } else {
          add_pred(   /* R.0:0.0:1 */
                     1.2640455235715142);
          if (defined_attr(1)) {  /* R.0:0.0:1.0 */
            if (double_attr(1) <= 0.015) {
              add_pred(   /* R.0:0.0:1.0:0 */
                         0.10048738220314965);
              if (defined_attr(2)) {  /* R.0:0.0:1.0:0.0 */
                if (double_attr(2) <= 0.975) {
                  add_pred(   /* R.0:0.0:1.0:0.0:0 */
                             -0.32543468514852736);
                } else {
                  add_pred(   /* R.0:0.0:1.0:0.0:1 */
                             0.14857447034823285);
                }
              }
            } else {
              add_pred(   /* R.0:0.0:1.0:1 */
                         -0.688303490412506);
            }
          }
          if (defined_attr(0)) {  /* R.0:0.0:1.1 */
            if (double_attr(0) <= 0.045) {
              add_pred(   /* R.0:0.0:1.1:0 */
                         0.08865591129249241);
            } else {
              add_pred(   /* R.0:0.0:1.1:1 */
                         -0.05309835210683352);
              if (defined_attr(0)) {  /* R.0:0.0:1.1:1.0 */
                if (double_attr(0) <= 0.125) {
                  add_pred(   /* R.0:0.0:1.1:1.0:0 */
                             -0.15248410916831712);
                  if (defined_attr(1)) {  /* R.0:0.0:1.1:1.0:0.0 */
                    if (double_attr(1) <= 0.08499999999999999) {
                      add_pred(   /* R.0:0.0:1.1:1.0:0.0:0 */
                                 0.12829275484731614);
                      if (defined_attr(2)) {  /* R.0:0.0:1.1:1.0:0.0:0.0 */
                        if (double_attr(2) <= 0.785) {
                          add_pred(   /* R.0:0.0:1.1:1.0:0.0:0.0:0 */
                                     0.2082455091811474);
                        } else {
                          add_pred(   /* R.0:0.0:1.1:1.0:0.0:0.0:1 */
                                     -0.16256193009597739);
                        }
                      }
                    } else {
                      add_pred(   /* R.0:0.0:1.1:1.0:0.0:1 */
                                 -0.4249310649117495);
                    }
                  }
                } else {
                  add_pred(   /* R.0:0.0:1.1:1.0:1 */
                             0.06846538158361722);
                }
              }
            }
          }
        }
      }
      if (defined_attr(0)) {  /* R.0:0.1 */
        if (double_attr(0) <= 0.025) {
          add_pred(   /* R.0:0.1:0 */
                     0.19565637469108965);
        } else {
          add_pred(   /* R.0:0.1:1 */
                     -0.049006067630972726);
          if (defined_attr(0)) {  /* R.0:0.1:1.0 */
            if (double_attr(0) <= 0.175) {
              add_pred(   /* R.0:0.1:1.0:0 */
                         -0.04261612652154022);
            } else {
              add_pred(   /* R.0:0.1:1.0:1 */
                         0.18490359201523487);
              if (defined_attr(1)) {  /* R.0:0.1:1.0:1.0 */
                if (double_attr(1) <= 0.055) {
                  add_pred(   /* R.0:0.1:1.0:1.0:0 */
                             -0.12050278737430256);
                } else {
                  add_pred(   /* R.0:0.1:1.0:1.0:1 */
                             0.1862692419554624);
                  if (defined_attr(2)) {  /* R.0:0.1:1.0:1.0:1.0 */
                    if (double_attr(2) <= 0.855) {
                      add_pred(   /* R.0:0.1:1.0:1.0:1.0:0 */
                                 -0.051381326360973735);
                    } else {
                      add_pred(   /* R.0:0.1:1.0:1.0:1.0:1 */
                                 1.0540738715458429);
                    }
                  }
                }
              }
            }
          }
        }
      }
    } else {
      add_pred(   /* R.0:1 */
                 0.7640596288249797);
      if (defined_attr(1)) {  /* R.0:1.0 */
        if (double_attr(1) <= 0.07500000000000001) {
          add_pred(   /* R.0:1.0:0 */
                     -0.29394251701802937);
          if (defined_attr(1)) {  /* R.0:1.0:0.0 */
            if (double_attr(1) <= 0.045) {
              add_pred(   /* R.0:1.0:0.0:0 */
                         -0.10446221377472567);
              if (defined_attr(2)) {  /* R.0:1.0:0.0:0.0 */
                if (double_attr(2) <= 0.265) {
                  add_pred(   /* R.0:1.0:0.0:0.0:0 */
                             0.2893879885006054);
                } else {
                  add_pred(   /* R.0:1.0:0.0:0.0:1 */
                             -0.012576888240246028);
                }
              }
            } else {
              add_pred(   /* R.0:1.0:0.0:1 */
                         0.16760954503868353);
            }
          }
          if (defined_attr(0)) {  /* R.0:1.0:0.1 */
            if (double_attr(0) <= 0.865) {
              add_pred(   /* R.0:1.0:0.1:0 */
                         0.02596639887521783);
              if (defined_attr(0)) {  /* R.0:1.0:0.1:0.0 */
                if (double_attr(0) <= 0.615) {
                  add_pred(   /* R.0:1.0:0.1:0.0:0 */
                             -0.05044185800294755);
                } else {
                  add_pred(   /* R.0:1.0:0.1:0.0:1 */
                             0.12924798915089486);
                }
              }
              if (defined_attr(0)) {  /* R.0:1.0:0.1:0.1 */
                if (double_attr(0) <= 0.705) {
                  add_pred(   /* R.0:1.0:0.1:0.1:0 */
                             0.0036654163202739292);
                } else {
                  add_pred(   /* R.0:1.0:0.1:0.1:1 */
                             -0.1696327877587653);
                }
              }
            } else {
              add_pred(   /* R.0:1.0:0.1:1 */
                         -0.31214921079558616);
              if (defined_attr(2)) {  /* R.0:1.0:0.1:1.0 */
                if (double_attr(2) <= 0.425) {
                  add_pred(   /* R.0:1.0:0.1:1.0:0 */
                             0.3316145886594319);
                } else {
                  add_pred(   /* R.0:1.0:0.1:1.0:1 */
                             -0.11386185140007556);
                  if (defined_attr(2)) {  /* R.0:1.0:0.1:1.0:1.0 */
                    if (double_attr(2) <= 0.575) {
                      add_pred(   /* R.0:1.0:0.1:1.0:1.0:0 */
                                 -0.16214053557660166);
                    } else {
                      add_pred(   /* R.0:1.0:0.1:1.0:1.0:1 */
                                 0.16692775413713334);
                    }
                  }
                }
              }
            }
          }
        } else {
          add_pred(   /* R.0:1.0:1 */
                     0.257950113064126);
          if (defined_attr(2)) {  /* R.0:1.0:1.0 */
            if (double_attr(2) <= 0.035) {
              add_pred(   /* R.0:1.0:1.0:0 */
                         -2.0074072208214124);
              if (defined_attr(2)) {  /* R.0:1.0:1.0:0.0 */
                if (double_attr(2) <= 0.015) {
                  add_pred(   /* R.0:1.0:1.0:0.0:0 */
                             0.1445398783374957);
                } else {
                  add_pred(   /* R.0:1.0:1.0:0.0:1 */
                             0.7030298616111295);
                }
              }
            } else {
              add_pred(   /* R.0:1.0:1.0:1 */
                         0.041231153332789344);
              if (defined_attr(2)) {  /* R.0:1.0:1.0:1.0 */
                if (double_attr(2) <= 0.065) {
                  add_pred(   /* R.0:1.0:1.0:1.0:0 */
                             -0.6708572397690892);
                } else {
                  add_pred(   /* R.0:1.0:1.0:1.0:1 */
                             0.011529549321492022);
                }
              }
            }
          }
          if (defined_attr(1)) {  /* R.0:1.0:1.1 */
            if (double_attr(1) <= 0.175) {
              add_pred(   /* R.0:1.0:1.1:0 */
                         -0.14925998416361366);
              if (defined_attr(1)) {  /* R.0:1.0:1.1:0.0 */
                if (double_attr(1) <= 0.11499999999999999) {
                  add_pred(   /* R.0:1.0:1.1:0.0:0 */
                             -0.11479148928469246);
                } else {
                  add_pred(   /* R.0:1.0:1.1:0.0:1 */
                             0.0667516228219089);
                  if (defined_attr(2)) {  /* R.0:1.0:1.1:0.0:1.0 */
                    if (double_attr(2) <= 0.355) {
                      add_pred(   /* R.0:1.0:1.1:0.0:1.0:0 */
                                 -0.07510086480811791);
                    } else {
                      add_pred(   /* R.0:1.0:1.1:0.0:1.0:1 */
                                 0.08015109159032224);
                    }
                  }
                }
              }
            } else {
              add_pred(   /* R.0:1.0:1.1:1 */
                         0.17877333550458638);
              if (defined_attr(2)) {  /* R.0:1.0:1.1:1.0 */
                if (double_attr(2) <= 0.295) {
                  add_pred(   /* R.0:1.0:1.1:1.0:0 */
                             -0.19881341914075548);
                  if (defined_attr(2)) {  /* R.0:1.0:1.1:1.0:0.0 */
                    if (double_attr(2) <= 0.215) {
                      add_pred(   /* R.0:1.0:1.1:1.0:0.0:0 */
                                 -0.1252210938705958);
                    } else {
                      add_pred(   /* R.0:1.0:1.1:1.0:0.0:1 */
                                 0.13533861857254714);
                      if (defined_attr(1)) {  /* R.0:1.0:1.1:1.0:0.0:1.0 */
                        if (double_attr(1) <= 0.395) {
                          add_pred(   /* R.0:1.0:1.1:1.0:0.0:1.0:0 */
                                     -0.016205021735125075);
                        } else {
                          add_pred(   /* R.0:1.0:1.1:1.0:0.0:1.0:1 */
                                     0.6316527564773046);
                        }
                      }
                    }
                  }
                  if (defined_attr(0)) {  /* R.0:1.0:1.1:1.0:0.1 */
                    if (double_attr(0) <= 0.835) {
                      add_pred(   /* R.0:1.0:1.1:1.0:0.1:0 */
                                 -0.024381607124412848);
                    } else {
                      add_pred(   /* R.0:1.0:1.1:1.0:0.1:1 */
                                 0.5817585272632204);
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.0:1.1:1.0:1 */
                             0.3279247595466093);
                  if (defined_attr(1)) {  /* R.0:1.0:1.1:1.0:1.0 */
                    if (double_attr(1) <= 0.475) {
                      add_pred(   /* R.0:1.0:1.1:1.0:1.0:0 */
                                 -0.07911960970031617);
                      if (defined_attr(1)) {  /* R.0:1.0:1.1:1.0:1.0:0.0 */
                        if (double_attr(1) <= 0.325) {
                          add_pred(   /* R.0:1.0:1.1:1.0:1.0:0.0:0 */
                                     -0.056593872289645075);
                        } else {
                          add_pred(   /* R.0:1.0:1.1:1.0:1.0:0.0:1 */
                                     0.22645157986675632);
                        }
                      }
                    } else {
                      add_pred(   /* R.0:1.0:1.1:1.0:1.0:1 */
                                 0.7683062753978868);
                      if (defined_attr(2)) {  /* R.0:1.0:1.1:1.0:1.0:1.0 */
                        if (double_attr(2) <= 0.755) {
                          add_pred(   /* R.0:1.0:1.1:1.0:1.0:1.0:0 */
                                     -0.07313707296992261);
                        } else {
                          add_pred(   /* R.0:1.0:1.1:1.0:1.0:1.0:1 */
                                     3.468129092842998);
                        }
                      }
                      if (defined_attr(1)) {  /* R.0:1.0:1.1:1.0:1.0:1.1 */
                        if (double_attr(1) <= 0.635) {
                          add_pred(   /* R.0:1.0:1.1:1.0:1.0:1.1:0 */
                                     -0.0770140501180549);
                        } else {
                          add_pred(   /* R.0:1.0:1.1:1.0:1.0:1.1:1 */
                                     1.0064484305224433);
                        }
                      }
                    }
                  }
                }
              }
              if (defined_attr(0)) {  /* R.0:1.0:1.1:1.1 */
                if (double_attr(0) <= 0.595) {
                  add_pred(   /* R.0:1.0:1.1:1.1:0 */
                             0.11629447812691807);
                  if (defined_attr(1)) {  /* R.0:1.0:1.1:1.1:0.0 */
                    if (double_attr(1) <= 0.265) {
                      add_pred(   /* R.0:1.0:1.1:1.1:0.0:0 */
                                 -0.13108673602629525);
                    } else {
                      add_pred(   /* R.0:1.0:1.1:1.1:0.0:1 */
                                 0.14639378986123752);
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.0:1.1:1.1:1 */
                             -0.1709204769156537);
                  if (defined_attr(0)) {  /* R.0:1.0:1.1:1.1:1.0 */
                    if (double_attr(0) <= 0.725) {
                      add_pred(   /* R.0:1.0:1.1:1.1:1.0:0 */
                                 -0.0947134069789856);
                    } else {
                      add_pred(   /* R.0:1.0:1.1:1.1:1.0:1 */
                                 0.12998746778098944);
                      if (defined_attr(0)) {  /* R.0:1.0:1.1:1.1:1.0:1.0 */
                        if (double_attr(0) <= 0.945) {
                          add_pred(   /* R.0:1.0:1.1:1.1:1.0:1.0:0 */
                                     0.21165758473578503);
                          if (defined_attr(2)) {  /* R.0:1.0:1.1:1.1:1.0:1.0:0.0 */
                            if (double_attr(2) <= 0.245) {
                              add_pred(   /* R.0:1.0:1.1:1.1:1.0:1.0:0.0:0 */
                                         -0.38442021013524647);
                            } else {
                              add_pred(   /* R.0:1.0:1.1:1.1:1.0:1.0:0.0:1 */
                                         0.29907960149667545);
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.0:1.1:1.1:1.0:1.0:1 */
                                     -0.11329674725572629);
                        }
                      }
                    }
                  }
                }
              }
            }
          }
          if (defined_attr(0)) {  /* R.0:1.0:1.2 */
            if (double_attr(0) <= 0.555) {
              add_pred(   /* R.0:1.0:1.2:0 */
                         0.08009747412891893);
              if (defined_attr(2)) {  /* R.0:1.0:1.2:0.0 */
                if (double_attr(2) <= 0.335) {
                  add_pred(   /* R.0:1.0:1.2:0.0:0 */
                             -0.08447051617592118);
                } else {
                  add_pred(   /* R.0:1.0:1.2:0.0:1 */
                             0.11872043841600871);
                }
              }
              if (defined_attr(1)) {  /* R.0:1.0:1.2:0.1 */
                if (double_attr(1) <= 0.095) {
                  add_pred(   /* R.0:1.0:1.2:0.1:0 */
                             -0.12789444588177973);
                } else {
                  add_pred(   /* R.0:1.0:1.2:0.1:1 */
                             0.018574475345936432);
                }
              }
            } else {
              add_pred(   /* R.0:1.0:1.2:1 */
                         -0.04558479480571826);
            }
          }
        }
      }
      if (defined_attr(0)) {  /* R.0:1.1 */
        if (double_attr(0) <= 0.615) {
          add_pred(   /* R.0:1.1:0 */
                     0.08574145556344986);
          if (defined_attr(0)) {  /* R.0:1.1:0.0 */
            if (double_attr(0) <= 0.395) {
              add_pred(   /* R.0:1.1:0.0:0 */
                         -0.45719314785708154);
              if (defined_attr(0)) {  /* R.0:1.1:0.0:0.0 */
                if (double_attr(0) <= 0.245) {
                  add_pred(   /* R.0:1.1:0.0:0.0:0 */
                             -0.1809330959418757);
                } else {
                  add_pred(   /* R.0:1.1:0.0:0.0:1 */
                             0.13534223328005668);
                }
              }
              if (defined_attr(2)) {  /* R.0:1.1:0.0:0.1 */
                if (double_attr(2) <= 0.485) {
                  add_pred(   /* R.0:1.1:0.0:0.1:0 */
                             0.15536551562021894);
                } else {
                  add_pred(   /* R.0:1.1:0.0:0.1:1 */
                             -0.02072120683548481);
                }
              }
            } else {
              add_pred(   /* R.0:1.1:0.0:1 */
                         0.0722213391256716);
              if (defined_attr(0)) {  /* R.0:1.1:0.0:1.0 */
                if (double_attr(0) <= 0.425) {
                  add_pred(   /* R.0:1.1:0.0:1.0:0 */
                             -0.13211151193490536);
                } else {
                  add_pred(   /* R.0:1.1:0.0:1.0:1 */
                             -0.0010327790223728507);
                  if (defined_attr(0)) {  /* R.0:1.1:0.0:1.0:1.0 */
                    if (double_attr(0) <= 0.575) {
                      add_pred(   /* R.0:1.1:0.0:1.0:1.0:0 */
                                 0.013290677330811046);
                    } else {
                      add_pred(   /* R.0:1.1:0.0:1.0:1.0:1 */
                                 -0.06749056863367844);
                    }
                  }
                }
              }
            }
          }
        } else {
          add_pred(   /* R.0:1.1:1 */
                     -0.22018238334776513);
          if (defined_attr(0)) {  /* R.0:1.1:1.0 */
            if (double_attr(0) <= 0.635) {
              add_pred(   /* R.0:1.1:1.0:0 */
                         0.1390724776539485);
              if (defined_attr(2)) {  /* R.0:1.1:1.0:0.0 */
                if (double_attr(2) <= 0.265) {
                  add_pred(   /* R.0:1.1:1.0:0.0:0 */
                             0.15919367445280547);
                } else {
                  add_pred(   /* R.0:1.1:1.0:0.0:1 */
                             -0.05744990468648921);
                }
              }
            } else {
              add_pred(   /* R.0:1.1:1.0:1 */
                         -0.015112951124763506);
            }
          }
        }
      }
      if (defined_attr(2)) {  /* R.0:1.2 */
        if (double_attr(2) <= 0.595) {
          add_pred(   /* R.0:1.2:0 */
                     -0.08195684774120124);
        } else {
          add_pred(   /* R.0:1.2:1 */
                     0.20910262475810037);
          if (defined_attr(0)) {  /* R.0:1.2:1.0 */
            if (double_attr(0) <= 0.46499999999999997) {
              add_pred(   /* R.0:1.2:1.0:0 */
                         -0.15270874495077064);
            } else {
              add_pred(   /* R.0:1.2:1.0:1 */
                         0.08659319521959061);
              if (defined_attr(2)) {  /* R.0:1.2:1.0:1.0 */
                if (double_attr(2) <= 0.745) {
                  add_pred(   /* R.0:1.2:1.0:1.0:0 */
                             -0.13125640707948127);
                  if (defined_attr(0)) {  /* R.0:1.2:1.0:1.0:0.0 */
                    if (double_attr(0) <= 0.975) {
                      add_pred(   /* R.0:1.2:1.0:1.0:0.0:0 */
                                 0.02004073176057538);
                    } else {
                      add_pred(   /* R.0:1.2:1.0:1.0:0.0:1 */
                                 -0.536971466079604);
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.2:1.0:1.0:1 */
                             0.07199991822932002);
                }
              }
            }
          }
        }
      }
    }
  }
  if (defined_attr(2)) {  /* R.1 */
    if (double_attr(2) <= 0.985) {
      add_pred(   /* R.1:0 */
                 -0.0640711683349544);
      if (defined_attr(2)) {  /* R.1:0.0 */
        if (double_attr(2) <= 0.955) {
          add_pred(   /* R.1:0.0:0 */
                     -0.01487363010264159);
          if (defined_attr(2)) {  /* R.1:0.0:0.0 */
            if (double_attr(2) <= 0.925) {
              add_pred(   /* R.1:0.0:0.0:0 */
                         0.001792382735721774);
            } else {
              add_pred(   /* R.1:0.0:0.0:1 */
                         0.1844253377680816);
            }
          }
        } else {
          add_pred(   /* R.1:0.0:1 */
                     0.4468417774830055);
        }
      }
    } else {
      add_pred(   /* R.1:1 */
                 1.1176183442618337);
      if (defined_attr(2)) {  /* R.1:1.0 */
        if (double_attr(2) <= 0.995) {
          add_pred(   /* R.1:1.0:0 */
                     -0.21767704213690212);
        } else {
          add_pred(   /* R.1:1.0:1 */
                     0.05914032880574072);
        }
      }
    }
  }

  return finalize_pred();
}

