/*************************************
This program can be used to evaluate a jboost-trained classifier on new data.  
The code contains a single procedure:

  double green_predict(void **attr, double *ret)

The first argument attr is an array of pointers corresponding to the
attributes specified in the spec file.  Thus, if attribute i is text,
then attr[i] must be a char array; if attribute i is a number, then
*attr[i] must be a double; and if attribute i is finite, then *attr[i]
must be an int containing the index of the chosen value.  An undefined
attribute is indicated by setting attr[i] to NULL.

Specifically, these pointers are:

     index    attr.type    data.type   name
   ------------------------------------------
        0     number       double      H
        1     number       double      S
        2     number       double      V

The second argument ret is a pointer to an array of k doubles, where k
is the number of classes.  The scores for each of the k classes will
be stored in this array.  If ret is NULL, then no scores are stored.
In any case, green_predict returns the score for class 0 (=ret[0]).

These scores correspond to the classes as follows:

            index       class name
           ------------------------
               0        0
               1        1

This classifier was automatically generated by jboost on
Wed Jun 02 20:24:32 PDT 2010.
*************************************/
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <limits.h>
#include <float.h>

typedef double Prediction_t;
#define reset_pred()  {p = 0.0;}
#define add_pred(X) {p += (X);}
#define finalize_pred()  ((r) ? (r[1] = p , r[0] = -p) : -p)
#define defined_attr(X)  (attr[X])
#define int_attr(X)      (*((int *) attr[X]))
#define attr_contains_token(X,Y) (tokens[X][Y])
#define double_attr(X)   (*((double *) attr[X]))

#define WHITE_CHARS   " \t\n"
typedef struct hash_table_entry_s {
  char *key;
  int id;
  struct hash_table_entry_s *next;
} HashTableEntry_t;
static char *keys[] = {
};
#define num_keys  (0)
static HashTableEntry_t **hash_table = NULL;
#define hash_table_size  (1031)
static char *tokens[1];
static int text_attr[] = {};
#define num_text_attr  (0)
static char **text_patterns[] = {
};

static char **words;
static int num_words;
static int cur_word;
static char *pattern;
static int pattern_len;

static void set_pattern(int n, char **m_w, char *pat) {
  words = m_w;
  pattern = pat;
  cur_word = 0;
  num_words = n;
  pattern_len = strlen(pat);
}

#define more_tokens()  (cur_word <= num_words - pattern_len)

#define ADD_CHAR(S)  { \
  if (c >= buffer_size) { \
    buffer_size = 2 * buffer_size + 1; \
    buffer = (char *) realloc(buffer, buffer_size * sizeof(char)); \
  } \
  buffer[c++] = (S); \
}

static char *next_token(void) {
  static char *buffer = NULL;
  static int buffer_size = 0;
  int i, c;
  char *s;

  c = 0;
  for (s = pattern; *s; s++)
    ADD_CHAR(*s);

  for (i = 0; i < pattern_len; i++) {
    if (pattern[i] == '1') {
      ADD_CHAR(' ');
      for (s = words[cur_word + i]; *s; s++)
	ADD_CHAR(*s);
    }
  }
  ADD_CHAR('\0');
  cur_word++;
  return buffer;
}

static int
hash(char *s) {
  static int *coef = NULL;
  static int max_len = 0;
  int len = strlen(s);
  int i, h;

  if (len > max_len) {
    i = max_len;
    max_len = 2 * len;
    coef = (int *) realloc(coef, max_len * sizeof(int));
    for (; i < max_len; i++)
      coef[i] = random() % hash_table_size;
  }

  h = 0;
  for (i = 0; i < len; i++) {
     if (h >= INT_MAX - (hash_table_size - 1) * 255)
       h = h % hash_table_size;
     h += coef[i] * s[i];
  }
  return (h % hash_table_size);
}

double green_predict(void **attr, double *r) {
  int i, j, h, a;
  HashTableEntry_t *entry;
  char *s;
  static char **words = NULL;
  static int max_word_list_size = 0;
  int num_words;
  static char *buffer = NULL;
  static int buffer_size = 0;
  char **pat;

  Prediction_t p;

  if (!hash_table) {
    hash_table = (HashTableEntry_t **)
      malloc(hash_table_size * sizeof(HashTableEntry_t *));
    for (i = 0; i < hash_table_size; i++)
      hash_table[i] = NULL;
    for (i = 0; i < num_keys; i++) {
      h = hash(keys[i]);
      entry = (HashTableEntry_t *) malloc(sizeof(HashTableEntry_t));
      entry->key = keys[i];
      entry->id = i;
      entry->next = hash_table[h];
      hash_table[h] = entry;
    }
    for (i = 0; i < num_text_attr; i++)
      tokens[text_attr[i]] = (char *) malloc(num_keys * sizeof(char));
  }

  for (i = 0; i < num_text_attr; i++) {
    a = text_attr[i];
    if (!defined_attr(a))
      continue;
    for (j = 0; j < num_keys; j++)
      tokens[a][j] = 0;

    while (strlcpy(buffer, attr[a], buffer_size) >= buffer_size) {
      buffer_size = 2 * strlen(attr[a]);
      buffer = (char *) realloc(buffer, (buffer_size+1) * sizeof(char));
    }
    num_words = 0;
    for (s = strtok(buffer, WHITE_CHARS); s; s = strtok(NULL, WHITE_CHARS)) {
      if (num_words >= max_word_list_size) {
        max_word_list_size = 2 * max_word_list_size + 1;
        words = (char **) realloc(words, max_word_list_size * sizeof(char *));
      }
      words[num_words++] = s;
    }
    for (pat = text_patterns[i]; *pat; pat++) {
      set_pattern(num_words, words, *pat);
      while (more_tokens()) {
        s = next_token();
        for (entry = hash_table[hash(s)]; entry; entry = entry->next)
          if (!strcmp(entry->key, s)) {
            tokens[a][entry->id] = 1;
            break;
          }
        }
      }
  }

  reset_pred();

  add_pred(   /* R */
             -1.0392143460243186);
  if (defined_attr(1)) {  /* R.0 */
    if (double_attr(1) <= 0.135) {
      add_pred(   /* R.0:0 */
                 -0.8426120116293646);
      if (defined_attr(2)) {  /* R.0:0.0 */
        if (double_attr(2) <= 0.255) {
          add_pred(   /* R.0:0.0:0 */
                     0.7640752421141751);
          if (defined_attr(0)) {  /* R.0:0.0:0.0 */
            if (double_attr(0) <= 0.545) {
              add_pred(   /* R.0:0.0:0.0:0 */
                         0.13298053904225657);
            } else {
              add_pred(   /* R.0:0.0:0.0:1 */
                         -0.4391669963367437);
            }
          }
          if (defined_attr(2)) {  /* R.0:0.0:0.1 */
            if (double_attr(2) <= 0.185) {
              add_pred(   /* R.0:0.0:0.1:0 */
                         0.16185843362854677);
            } else {
              add_pred(   /* R.0:0.0:0.1:1 */
                         -0.22522392645125394);
            }
          }
        } else {
          add_pred(   /* R.0:0.0:1 */
                     -0.18770073642638307);
          if (defined_attr(1)) {  /* R.0:0.0:1.0 */
            if (double_attr(1) <= 0.10500000000000001) {
              add_pred(   /* R.0:0.0:1.0:0 */
                         -0.17200160457260838);
              if (defined_attr(1)) {  /* R.0:0.0:1.0:0.0 */
                if (double_attr(1) <= 0.045) {
                  add_pred(   /* R.0:0.0:1.0:0.0:0 */
                             -0.14563917228656034);
                } else {
                  add_pred(   /* R.0:0.0:1.0:0.0:1 */
                             0.17858238052698566);
                  if (defined_attr(0)) {  /* R.0:0.0:1.0:0.0:1.0 */
                    if (double_attr(0) <= 0.46499999999999997) {
                      add_pred(   /* R.0:0.0:1.0:0.0:1.0:0 */
                                 0.014466718022636958);
                      if (defined_attr(2)) {  /* R.0:0.0:1.0:0.0:1.0:0.0 */
                        if (double_attr(2) <= 0.46499999999999997) {
                          add_pred(   /* R.0:0.0:1.0:0.0:1.0:0.0:0 */
                                     0.14894904844493093);
                          if (defined_attr(1)) {  /* R.0:0.0:1.0:0.0:1.0:0.0:0.0 */
                            if (double_attr(1) <= 0.08499999999999999) {
                              add_pred(   /* R.0:0.0:1.0:0.0:1.0:0.0:0.0:0 */
                                         -0.11834080797681246);
                            } else {
                              add_pred(   /* R.0:0.0:1.0:0.0:1.0:0.0:0.0:1 */
                                         0.28279554953095687);
                            }
                          }
                        } else {
                          add_pred(   /* R.0:0.0:1.0:0.0:1.0:0.0:1 */
                                     -0.09691938573650812);
                          if (defined_attr(2)) {  /* R.0:0.0:1.0:0.0:1.0:0.0:1.0 */
                            if (double_attr(2) <= 0.505) {
                              add_pred(   /* R.0:0.0:1.0:0.0:1.0:0.0:1.0:0 */
                                         -0.3089445923842262);
                            } else {
                              add_pred(   /* R.0:0.0:1.0:0.0:1.0:0.0:1.0:1 */
                                         -0.01225678156908757);
                            }
                          }
                        }
                      }
                    } else {
                      add_pred(   /* R.0:0.0:1.0:0.0:1.0:1 */
                                 -0.45257967112897607);
                    }
                  }
                }
              }
              if (defined_attr(2)) {  /* R.0:0.0:1.0:0.1 */
                if (double_attr(2) <= 0.305) {
                  add_pred(   /* R.0:0.0:1.0:0.1:0 */
                             0.30946771275426027);
                } else {
                  add_pred(   /* R.0:0.0:1.0:0.1:1 */
                             -0.0233566645368012);
                  if (defined_attr(2)) {  /* R.0:0.0:1.0:0.1:1.0 */
                    if (double_attr(2) <= 0.565) {
                      add_pred(   /* R.0:0.0:1.0:0.1:1.0:0 */
                                 -0.060146122535843255);
                    } else {
                      add_pred(   /* R.0:0.0:1.0:0.1:1.0:1 */
                                 0.20307346916088045);
                      if (defined_attr(1)) {  /* R.0:0.0:1.0:0.1:1.0:1.0 */
                        if (double_attr(1) <= 0.095) {
                          add_pred(   /* R.0:0.0:1.0:0.1:1.0:1.0:0 */
                                     0.11798984965060957);
                        } else {
                          add_pred(   /* R.0:0.0:1.0:0.1:1.0:1.0:1 */
                                     0.38316973086263717);
                        }
                      }
                    }
                  }
                }
              }
            } else {
              add_pred(   /* R.0:0.0:1.0:1 */
                         0.6222613612159946);
              if (defined_attr(2)) {  /* R.0:0.0:1.0:1.0 */
                if (double_attr(2) <= 0.615) {
                  add_pred(   /* R.0:0.0:1.0:1.0:0 */
                             -0.15939964780141244);
                  if (defined_attr(0)) {  /* R.0:0.0:1.0:1.0:0.0 */
                    if (double_attr(0) <= 0.10500000000000001) {
                      add_pred(   /* R.0:0.0:1.0:1.0:0.0:0 */
                                 -0.6365818986040945);
                      if (defined_attr(2)) {  /* R.0:0.0:1.0:1.0:0.0:0.0 */
                        if (double_attr(2) <= 0.545) {
                          add_pred(   /* R.0:0.0:1.0:1.0:0.0:0.0:0 */
                                     0.8058438761721083);
                        } else {
                          add_pred(   /* R.0:0.0:1.0:1.0:0.0:0.0:1 */
                                     -0.4595627064887265);
                          if (defined_attr(0)) {  /* R.0:0.0:1.0:1.0:0.0:0.0:1.0 */
                            if (double_attr(0) <= 0.055) {
                              add_pred(   /* R.0:0.0:1.0:1.0:0.0:0.0:1.0:0 */
                                         1.6202472657659484);
                            } else {
                              add_pred(   /* R.0:0.0:1.0:1.0:0.0:0.0:1.0:1 */
                                         -0.038444079351276826);
                            }
                          }
                        }
                      }
                    } else {
                      add_pred(   /* R.0:0.0:1.0:1.0:0.0:1 */
                                 0.24438163732989254);
                    }
                  }
                  if (defined_attr(1)) {  /* R.0:0.0:1.0:1.0:0.1 */
                    if (double_attr(1) <= 0.11499999999999999) {
                      add_pred(   /* R.0:0.0:1.0:1.0:0.1:0 */
                                 -0.0843376803801444);
                    } else {
                      add_pred(   /* R.0:0.0:1.0:1.0:0.1:1 */
                                 0.19692653799779297);
                    }
                  }
                } else {
                  add_pred(   /* R.0:0.0:1.0:1.0:1 */
                             0.759833692591257);
                  if (defined_attr(0)) {  /* R.0:0.0:1.0:1.0:1.0 */
                    if (double_attr(0) <= 0.14500000000000002) {
                      add_pred(   /* R.0:0.0:1.0:1.0:1.0:0 */
                                 -0.011145464762502843);
                    } else {
                      add_pred(   /* R.0:0.0:1.0:1.0:1.0:1 */
                                 -0.7670582582421551);
                    }
                  }
                }
              }
            }
          }
        }
      }
    } else {
      add_pred(   /* R.0:1 */
                 0.7168889924354311);
      if (defined_attr(0)) {  /* R.0:1.0 */
        if (double_attr(0) <= 0.425) {
          add_pred(   /* R.0:1.0:0 */
                     0.4992658831638774);
          if (defined_attr(0)) {  /* R.0:1.0:0.0 */
            if (double_attr(0) <= 0.055) {
              add_pred(   /* R.0:1.0:0.0:0 */
                         -1.4972294883095694);
              if (defined_attr(0)) {  /* R.0:1.0:0.0:0.0 */
                if (double_attr(0) <= 0.025) {
                  add_pred(   /* R.0:1.0:0.0:0.0:0 */
                             -0.4325416244851402);
                } else {
                  add_pred(   /* R.0:1.0:0.0:0.0:1 */
                             0.2269612662730739);
                }
              }
            } else {
              add_pred(   /* R.0:1.0:0.0:1 */
                         -0.047471209475502985);
              if (defined_attr(1)) {  /* R.0:1.0:0.0:1.0 */
                if (double_attr(1) <= 0.155) {
                  add_pred(   /* R.0:1.0:0.0:1.0:0 */
                             -0.6003978660462571);
                } else {
                  add_pred(   /* R.0:1.0:0.0:1.0:1 */
                             -0.00842195478283732);
                  if (defined_attr(2)) {  /* R.0:1.0:0.0:1.0:1.0 */
                    if (double_attr(2) <= 0.135) {
                      add_pred(   /* R.0:1.0:0.0:1.0:1.0:0 */
                                 -0.6347779690347785);
                    } else {
                      add_pred(   /* R.0:1.0:0.0:1.0:1.0:1 */
                                 0.07797875360266382);
                      if (defined_attr(1)) {  /* R.0:1.0:0.0:1.0:1.0:1.0 */
                        if (double_attr(1) <= 0.175) {
                          add_pred(   /* R.0:1.0:0.0:1.0:1.0:1.0:0 */
                                     -0.23814222700987267);
                        } else {
                          add_pred(   /* R.0:1.0:0.0:1.0:1.0:1.0:1 */
                                     0.008051047136014823);
                        }
                      }
                      if (defined_attr(2)) {  /* R.0:1.0:0.0:1.0:1.0:1.1 */
                        if (double_attr(2) <= 0.175) {
                          add_pred(   /* R.0:1.0:0.0:1.0:1.0:1.1:0 */
                                     -0.27169374047412903);
                        } else {
                          add_pred(   /* R.0:1.0:0.0:1.0:1.0:1.1:1 */
                                     -0.0012537599955261215);
                        }
                      }
                    }
                  }
                }
              }
              if (defined_attr(1)) {  /* R.0:1.0:0.0:1.1 */
                if (double_attr(1) <= 0.195) {
                  add_pred(   /* R.0:1.0:0.0:1.1:0 */
                             -0.22134542490007034);
                } else {
                  add_pred(   /* R.0:1.0:0.0:1.1:1 */
                             0.0018719841068484285);
                  if (defined_attr(0)) {  /* R.0:1.0:0.0:1.1:1.0 */
                    if (double_attr(0) <= 0.33999999999999997) {
                      add_pred(   /* R.0:1.0:0.0:1.1:1.0:0 */
                                 0.04567955410431615);
                      if (defined_attr(2)) {  /* R.0:1.0:0.0:1.1:1.0:0.0 */
                        if (double_attr(2) <= 0.595) {
                          add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:0 */
                                     0.04614634438221172);
                          if (defined_attr(2)) {  /* R.0:1.0:0.0:1.1:1.0:0.0:0.0 */
                            if (double_attr(2) <= 0.095) {
                              add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:0.0:0 */
                                         -0.28443558988351436);
                            } else {
                              add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:0.0:1 */
                                         0.01936956122915572);
                            }
                          }
                        } else {
                          add_pred(   /* R.0:1.0:0.0:1.1:1.0:0.0:1 */
                                     -0.4520791123308703);
                        }
                      }
                    } else {
                      add_pred(   /* R.0:1.0:0.0:1.1:1.0:1 */
                                 -0.9731678874475715);
                    }
                  }
                }
              }
              if (defined_attr(0)) {  /* R.0:1.0:0.0:1.2 */
                if (double_attr(0) <= 0.065) {
                  add_pred(   /* R.0:1.0:0.0:1.2:0 */
                             -0.6025101109367578);
                } else {
                  add_pred(   /* R.0:1.0:0.0:1.2:1 */
                             -0.01678965421825168);
                }
              }
            }
          }
        } else {
          add_pred(   /* R.0:1.0:1 */
                     -2.234948481222696);
          if (defined_attr(1)) {  /* R.0:1.0:1.0 */
            if (double_attr(1) <= 0.175) {
              add_pred(   /* R.0:1.0:1.0:0 */
                         0.5055796716308678);
            } else {
              add_pred(   /* R.0:1.0:1.0:1 */
                         -0.22439149203201494);
              if (defined_attr(1)) {  /* R.0:1.0:1.0:1.0 */
                if (double_attr(1) <= 0.245) {
                  add_pred(   /* R.0:1.0:1.0:1.0:0 */
                             0.45677162748842276);
                } else {
                  add_pred(   /* R.0:1.0:1.0:1.0:1 */
                             -0.09729503385184782);
                }
              }
            }
          }
          if (defined_attr(2)) {  /* R.0:1.0:1.1 */
            if (double_attr(2) <= 0.475) {
              add_pred(   /* R.0:1.0:1.1:0 */
                         0.10569509998848564);
            } else {
              add_pred(   /* R.0:1.0:1.1:1 */
                         0.9387075699889058);
            }
          }
        }
      }
    }
  }
  if (defined_attr(2)) {  /* R.1 */
    if (double_attr(2) <= 0.415) {
      add_pred(   /* R.1:0 */
                 0.6266683979564868);
      if (defined_attr(2)) {  /* R.1:0.0 */
        if (double_attr(2) <= 0.015) {
          add_pred(   /* R.1:0.0:0 */
                     -2.6992663632597758);
          if (defined_attr(2)) {  /* R.1:0.0:0.0 */
            if (double_attr(2) <= 0.0050) {
              add_pred(   /* R.1:0.0:0.0:0 */
                         -0.5462465986899705);
            } else {
              add_pred(   /* R.1:0.0:0.0:1 */
                         0.8980050181421925);
            }
          }
        } else {
          add_pred(   /* R.1:0.0:1 */
                     0.1986765708919961);
          if (defined_attr(2)) {  /* R.1:0.0:1.0 */
            if (double_attr(2) <= 0.355) {
              add_pred(   /* R.1:0.0:1.0:0 */
                         0.13926835750091843);
              if (defined_attr(1)) {  /* R.1:0.0:1.0:0.0 */
                if (double_attr(1) <= 0.825) {
                  add_pred(   /* R.1:0.0:1.0:0.0:0 */
                             0.011524171832437192);
                  if (defined_attr(2)) {  /* R.1:0.0:1.0:0.0:0.0 */
                    if (double_attr(2) <= 0.025) {
                      add_pred(   /* R.1:0.0:1.0:0.0:0.0:0 */
                                 -0.788431584853439);
                    } else {
                      add_pred(   /* R.1:0.0:1.0:0.0:0.0:1 */
                                 -0.03241148463764752);
                    }
                  }
                } else {
                  add_pred(   /* R.1:0.0:1.0:0.0:1 */
                             -1.6334107917542262);
                }
              }
            } else {
              add_pred(   /* R.1:0.0:1.0:1 */
                         -0.6178722661707461);
              if (defined_attr(1)) {  /* R.1:0.0:1.0:1.0 */
                if (double_attr(1) <= 0.295) {
                  add_pred(   /* R.1:0.0:1.0:1.0:0 */
                             0.21197816725509075);
                  if (defined_attr(1)) {  /* R.1:0.0:1.0:1.0:0.0 */
                    if (double_attr(1) <= 0.035) {
                      add_pred(   /* R.1:0.0:1.0:1.0:0.0:0 */
                                 -0.42509775359142465);
                      if (defined_attr(0)) {  /* R.1:0.0:1.0:1.0:0.0:0.0 */
                        if (double_attr(0) <= 0.515) {
                          add_pred(   /* R.1:0.0:1.0:1.0:0.0:0.0:0 */
                                     -0.1099799392754927);
                        } else {
                          add_pred(   /* R.1:0.0:1.0:1.0:0.0:0.0:1 */
                                     0.8349372210713529);
                        }
                      }
                    } else {
                      add_pred(   /* R.1:0.0:1.0:1.0:0.0:1 */
                                 0.139875869941382);
                    }
                  }
                } else {
                  add_pred(   /* R.1:0.0:1.0:1.0:1 */
                             -0.6532755493554973);
                }
              }
            }
          }
        }
      }
      if (defined_attr(0)) {  /* R.1:0.1 */
        if (double_attr(0) <= 0.08499999999999999) {
          add_pred(   /* R.1:0.1:0 */
                     -0.252865000517291);
          if (defined_attr(2)) {  /* R.1:0.1:0.0 */
            if (double_attr(2) <= 0.125) {
              add_pred(   /* R.1:0.1:0.0:0 */
                         0.13431412166521012);
            } else {
              add_pred(   /* R.1:0.1:0.0:1 */
                         -0.15753422945047924);
            }
          }
        } else {
          add_pred(   /* R.1:0.1:1 */
                     0.02233057513908324);
          if (defined_attr(1)) {  /* R.1:0.1:1.0 */
            if (double_attr(1) <= 0.245) {
              add_pred(   /* R.1:0.1:1.0:0 */
                         -0.03970041917756199);
            } else {
              add_pred(   /* R.1:0.1:1.0:1 */
                         0.09582694367566899);
            }
          }
        }
      }
    } else {
      add_pred(   /* R.1:1 */
                 -1.0490119598527057);
      if (defined_attr(1)) {  /* R.1:1.0 */
        if (double_attr(1) <= 0.275) {
          add_pred(   /* R.1:1.0:0 */
                     0.16533969063979229);
          if (defined_attr(2)) {  /* R.1:1.0:0.0 */
            if (double_attr(2) <= 0.505) {
              add_pred(   /* R.1:1.0:0.0:0 */
                         0.4682975763331817);
              if (defined_attr(0)) {  /* R.1:1.0:0.0:0.0 */
                if (double_attr(0) <= 0.435) {
                  add_pred(   /* R.1:1.0:0.0:0.0:0 */
                             -0.0371877146938389);
                } else {
                  add_pred(   /* R.1:1.0:0.0:0.0:1 */
                             0.524483960785666);
                }
              }
            } else {
              add_pred(   /* R.1:1.0:0.0:1 */
                         -0.17837373056488648);
              if (defined_attr(0)) {  /* R.1:1.0:0.0:1.0 */
                if (double_attr(0) <= 0.175) {
                  add_pred(   /* R.1:1.0:0.0:1.0:0 */
                             -0.023005217709602243);
                  if (defined_attr(1)) {  /* R.1:1.0:0.0:1.0:0.0 */
                    if (double_attr(1) <= 0.125) {
                      add_pred(   /* R.1:1.0:0.0:1.0:0.0:0 */
                                 -0.22889841588542967);
                      if (defined_attr(2)) {  /* R.1:1.0:0.0:1.0:0.0:0.0 */
                        if (double_attr(2) <= 0.595) {
                          add_pred(   /* R.1:1.0:0.0:1.0:0.0:0.0:0 */
                                     -0.17859265375307345);
                          if (defined_attr(0)) {  /* R.1:1.0:0.0:1.0:0.0:0.0:0.0 */
                            if (double_attr(0) <= 0.14500000000000002) {
                              add_pred(   /* R.1:1.0:0.0:1.0:0.0:0.0:0.0:0 */
                                         -0.21107345641430045);
                            } else {
                              add_pred(   /* R.1:1.0:0.0:1.0:0.0:0.0:0.0:1 */
                                         0.5147150602309912);
                            }
                          }
                          if (defined_attr(1)) {  /* R.1:1.0:0.0:1.0:0.0:0.0:0.1 */
                            if (double_attr(1) <= 0.055) {
                              add_pred(   /* R.1:1.0:0.0:1.0:0.0:0.0:0.1:0 */
                                         0.4990916119126316);
                            } else {
                              add_pred(   /* R.1:1.0:0.0:1.0:0.0:0.0:0.1:1 */
                                         -0.07528561844419315);
                              if (defined_attr(0)) {  /* R.1:1.0:0.0:1.0:0.0:0.0:0.1:1.0 */
                                if (double_attr(0) <= 0.07500000000000001) {
                                  add_pred(   /* R.1:1.0:0.0:1.0:0.0:0.0:0.1:1.0:0 */
                                             0.6088030916464205);
                                } else {
                                  add_pred(   /* R.1:1.0:0.0:1.0:0.0:0.0:0.1:1.0:1 */
                                             -0.04882765238735409);
                                }
                              }
                            }
                          }
                        } else {
                          add_pred(   /* R.1:1.0:0.0:1.0:0.0:0.0:1 */
                                     0.5787487401874297);
                          if (defined_attr(1)) {  /* R.1:1.0:0.0:1.0:0.0:0.0:1.0 */
                            if (double_attr(1) <= 0.015) {
                              add_pred(   /* R.1:1.0:0.0:1.0:0.0:0.0:1.0:0 */
                                         -3.6824823234501394);
                            } else {
                              add_pred(   /* R.1:1.0:0.0:1.0:0.0:0.0:1.0:1 */
                                         -0.10755237623486759);
                              if (defined_attr(2)) {  /* R.1:1.0:0.0:1.0:0.0:0.0:1.0:1.0 */
                                if (double_attr(2) <= 0.605) {
                                  add_pred(   /* R.1:1.0:0.0:1.0:0.0:0.0:1.0:1.0:0 */
                                             -0.5546396269683324);
                                } else {
                                  add_pred(   /* R.1:1.0:0.0:1.0:0.0:0.0:1.0:1.0:1 */
                                             0.08697859542366791);
                                }
                              }
                            }
                          }
                        }
                      }
                    } else {
                      add_pred(   /* R.1:1.0:0.0:1.0:0.0:1 */
                                 0.20897011900192713);
                      if (defined_attr(1)) {  /* R.1:1.0:0.0:1.0:0.0:1.0 */
                        if (double_attr(1) <= 0.265) {
                          add_pred(   /* R.1:1.0:0.0:1.0:0.0:1.0:0 */
                                     0.1311179850327532);
                          if (defined_attr(1)) {  /* R.1:1.0:0.0:1.0:0.0:1.0:0.0 */
                            if (double_attr(1) <= 0.14500000000000002) {
                              add_pred(   /* R.1:1.0:0.0:1.0:0.0:1.0:0.0:0 */
                                         -0.20793310490785769);
                              if (defined_attr(2)) {  /* R.1:1.0:0.0:1.0:0.0:1.0:0.0:0.0 */
                                if (double_attr(2) <= 0.585) {
                                  add_pred(   /* R.1:1.0:0.0:1.0:0.0:1.0:0.0:0.0:0 */
                                             -0.2914340901746992);
                                  if (defined_attr(0)) {  /* R.1:1.0:0.0:1.0:0.0:1.0:0.0:0.0:0.0 */
                                    if (double_attr(0) <= 0.13) {
                                      add_pred(   /* R.1:1.0:0.0:1.0:0.0:1.0:0.0:0.0:0.0:0 */
                                                 -0.2647726652427983);
                                    } else {
                                      add_pred(   /* R.1:1.0:0.0:1.0:0.0:1.0:0.0:0.0:0.0:1 */
                                                 0.4700420449168726);
                                    }
                                  }
                                } else {
                                  add_pred(   /* R.1:1.0:0.0:1.0:0.0:1.0:0.0:0.0:1 */
                                             0.423520701933652);
                                }
                              }
                            } else {
                              add_pred(   /* R.1:1.0:0.0:1.0:0.0:1.0:0.0:1 */
                                         0.1649937466300099);
                            }
                          }
                        } else {
                          add_pred(   /* R.1:1.0:0.0:1.0:0.0:1.0:1 */
                                     -0.5066692993549234);
                        }
                      }
                    }
                  }
                  if (defined_attr(2)) {  /* R.1:1.0:0.0:1.0:0.1 */
                    if (double_attr(2) <= 0.535) {
                      add_pred(   /* R.1:1.0:0.0:1.0:0.1:0 */
                                 0.1819210825373671);
                    } else {
                      add_pred(   /* R.1:1.0:0.0:1.0:0.1:1 */
                                 -0.03043899677409887);
                    }
                  }
                } else {
                  add_pred(   /* R.1:1.0:0.0:1.0:1 */
                             0.3648108988553996);
                  if (defined_attr(2)) {  /* R.1:1.0:0.0:1.0:1.0 */
                    if (double_attr(2) <= 0.725) {
                      add_pred(   /* R.1:1.0:0.0:1.0:1.0:0 */
                                 0.24345655183607126);
                    } else {
                      add_pred(   /* R.1:1.0:0.0:1.0:1.0:1 */
                                 -0.5802527893938775);
                      if (defined_attr(0)) {  /* R.1:1.0:0.0:1.0:1.0:1.0 */
                        if (double_attr(0) <= 0.625) {
                          add_pred(   /* R.1:1.0:0.0:1.0:1.0:1.0:0 */
                                     0.03207757479142716);
                          if (defined_attr(0)) {  /* R.1:1.0:0.0:1.0:1.0:1.0:0.0 */
                            if (double_attr(0) <= 0.595) {
                              add_pred(   /* R.1:1.0:0.0:1.0:1.0:1.0:0.0:0 */
                                         -0.2568215321000102);
                            } else {
                              add_pred(   /* R.1:1.0:0.0:1.0:1.0:1.0:0.0:1 */
                                         0.9221180486676532);
                            }
                          }
                        } else {
                          add_pred(   /* R.1:1.0:0.0:1.0:1.0:1.0:1 */
                                     -3.6855863268182394);
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        } else {
          add_pred(   /* R.1:1.0:1 */
                     -0.4752888154733557);
          if (defined_attr(0)) {  /* R.1:1.0:1.0 */
            if (double_attr(0) <= 0.10500000000000001) {
              add_pred(   /* R.1:1.0:1.0:0 */
                         0.9078285729547011);
              if (defined_attr(1)) {  /* R.1:1.0:1.0:0.0 */
                if (double_attr(1) <= 0.525) {
                  add_pred(   /* R.1:1.0:1.0:0.0:0 */
                             -0.045203520034495806);
                } else {
                  add_pred(   /* R.1:1.0:1.0:0.0:1 */
                             -3.5182908384181273);
                }
              }
            } else {
              add_pred(   /* R.1:1.0:1.0:1 */
                         -0.2772181957591915);
              if (defined_attr(0)) {  /* R.1:1.0:1.0:1.0 */
                if (double_attr(0) <= 0.985) {
                  add_pred(   /* R.1:1.0:1.0:1.0:0 */
                             -0.20558061822291893);
                  if (defined_attr(2)) {  /* R.1:1.0:1.0:1.0:0.0 */
                    if (double_attr(2) <= 0.485) {
                      add_pred(   /* R.1:1.0:1.0:1.0:0.0:0 */
                                 0.1894894329525933);
                    } else {
                      add_pred(   /* R.1:1.0:1.0:1.0:0.0:1 */
                                 -0.28384800260595217);
                    }
                  }
                } else {
                  add_pred(   /* R.1:1.0:1.0:1.0:1 */
                             3.06200795183284);
                }
              }
            }
          }
        }
      }
      if (defined_attr(0)) {  /* R.1:1.1 */
        if (double_attr(0) <= 0.11499999999999999) {
          add_pred(   /* R.1:1.1:0 */
                     0.17429414897180118);
          if (defined_attr(2)) {  /* R.1:1.1:0.0 */
            if (double_attr(2) <= 0.495) {
              add_pred(   /* R.1:1.1:0.0:0 */
                         0.2543913248207349);
              if (defined_attr(0)) {  /* R.1:1.1:0.0:0.0 */
                if (double_attr(0) <= 0.045) {
                  add_pred(   /* R.1:1.1:0.0:0.0:0 */
                             -0.7712884646006586);
                } else {
                  add_pred(   /* R.1:1.1:0.0:0.0:1 */
                             0.06234890531488173);
                }
              }
            } else {
              add_pred(   /* R.1:1.1:0.0:1 */
                         -0.06550329293797237);
            }
          }
        } else {
          add_pred(   /* R.1:1.1:1 */
                     -0.06707104213246297);
          if (defined_attr(1)) {  /* R.1:1.1:1.0 */
            if (double_attr(1) <= 0.215) {
              add_pred(   /* R.1:1.1:1.0:0 */
                         0.07550593924907151);
            } else {
              add_pred(   /* R.1:1.1:1.0:1 */
                         -0.3275779588365139);
              if (defined_attr(1)) {  /* R.1:1.1:1.0:1.0 */
                if (double_attr(1) <= 0.275) {
                  add_pred(   /* R.1:1.1:1.0:1.0:0 */
                             -0.33904430280826625);
                  if (defined_attr(1)) {  /* R.1:1.1:1.0:1.0:0.0 */
                    if (double_attr(1) <= 0.235) {
                      add_pred(   /* R.1:1.1:1.0:1.0:0.0:0 */
                                 0.2436666357235484);
                    } else {
                      add_pred(   /* R.1:1.1:1.0:1.0:0.0:1 */
                                 -0.2859206736092341);
                    }
                  }
                } else {
                  add_pred(   /* R.1:1.1:1.0:1.0:1 */
                             0.18254895106521035);
                }
              }
            }
          }
        }
      }
      if (defined_attr(2)) {  /* R.1:1.2 */
        if (double_attr(2) <= 0.445) {
          add_pred(   /* R.1:1.2:0 */
                     0.43927162911261);
        } else {
          add_pred(   /* R.1:1.2:1 */
                     -0.04470069813611445);
        }
      }
    }
  }
  if (defined_attr(0)) {  /* R.2 */
    if (double_attr(0) <= 0.28500000000000003) {
      add_pred(   /* R.2:0 */
                 0.16397434825358123);
      if (defined_attr(0)) {  /* R.2:0.0 */
        if (double_attr(0) <= 0.135) {
          add_pred(   /* R.2:0.0:0 */
                     -0.1772626004180644);
        } else {
          add_pred(   /* R.2:0.0:1 */
                     0.17240663252760063);
          if (defined_attr(2)) {  /* R.2:0.0:1.0 */
            if (double_attr(2) <= 0.325) {
              add_pred(   /* R.2:0.0:1.0:0 */
                         0.20801483673569465);
            } else {
              add_pred(   /* R.2:0.0:1.0:1 */
                         -0.1786066845554318);
              if (defined_attr(1)) {  /* R.2:0.0:1.0:1.0 */
                if (double_attr(1) <= 0.345) {
                  add_pred(   /* R.2:0.0:1.0:1.0:0 */
                             -0.020765946643055106);
                } else {
                  add_pred(   /* R.2:0.0:1.0:1.0:1 */
                             -0.7976505959619176);
                  if (defined_attr(2)) {  /* R.2:0.0:1.0:1.0:1.0 */
                    if (double_attr(2) <= 0.375) {
                      add_pred(   /* R.2:0.0:1.0:1.0:1.0:0 */
                                 0.6116563261254641);
                    } else {
                      add_pred(   /* R.2:0.0:1.0:1.0:1.0:1 */
                                 -1.3142796549080014);
                    }
                  }
                }
              }
            }
          }
        }
      }
      if (defined_attr(1)) {  /* R.2:0.1 */
        if (double_attr(1) <= 0.065) {
          add_pred(   /* R.2:0.1:0 */
                     -0.37393415487988346);
          if (defined_attr(2)) {  /* R.2:0.1:0.0 */
            if (double_attr(2) <= 0.14500000000000002) {
              add_pred(   /* R.2:0.1:0.0:0 */
                         0.314206499393325);
              if (defined_attr(2)) {  /* R.2:0.1:0.0:0.0 */
                if (double_attr(2) <= 0.0050) {
                  add_pred(   /* R.2:0.1:0.0:0.0:0 */
                             -0.4844549129022472);
                } else {
                  add_pred(   /* R.2:0.1:0.0:0.0:1 */
                             0.378816244969524);
                }
              }
            } else {
              add_pred(   /* R.2:0.1:0.0:1 */
                         -0.12520630125418827);
            }
          }
        } else {
          add_pred(   /* R.2:0.1:1 */
                     0.0667880916666961);
        }
      }
      if (defined_attr(2)) {  /* R.2:0.2 */
        if (double_attr(2) <= 0.825) {
          add_pred(   /* R.2:0.2:0 */
                     0.013384287137517123);
        } else {
          add_pred(   /* R.2:0.2:1 */
                     -4.509897186306628);
        }
      }
      if (defined_attr(0)) {  /* R.2:0.3 */
        if (double_attr(0) <= 0.215) {
          add_pred(   /* R.2:0.3:0 */
                     0.027717119919702587);
        } else {
          add_pred(   /* R.2:0.3:1 */
                     -0.30055403260885377);
        }
      }
      if (defined_attr(2)) {  /* R.2:0.4 */
        if (double_attr(2) <= 0.805) {
          add_pred(   /* R.2:0.4:0 */
                     0.01904318242881016);
        } else {
          add_pred(   /* R.2:0.4:1 */
                     -1.2306882680461677);
        }
      }
    } else {
      add_pred(   /* R.2:1 */
                 -0.6132476566158002);
      if (defined_attr(2)) {  /* R.2:1.0 */
        if (double_attr(2) <= 0.135) {
          add_pred(   /* R.2:1.0:0 */
                     0.7236315969008038);
          if (defined_attr(2)) {  /* R.2:1.0:0.0 */
            if (double_attr(2) <= 0.095) {
              add_pred(   /* R.2:1.0:0.0:0 */
                         0.32857632172057377);
            } else {
              add_pred(   /* R.2:1.0:0.0:1 */
                         -0.2637151643887428);
            }
          }
        } else {
          add_pred(   /* R.2:1.0:1 */
                     -0.5095947967914443);
          if (defined_attr(1)) {  /* R.2:1.0:1.0 */
            if (double_attr(1) <= 0.07500000000000001) {
              add_pred(   /* R.2:1.0:1.0:0 */
                         0.3169201192488648);
            } else {
              add_pred(   /* R.2:1.0:1.0:1 */
                         -0.30528022456203446);
              if (defined_attr(2)) {  /* R.2:1.0:1.0:1.0 */
                if (double_attr(2) <= 0.215) {
                  add_pred(   /* R.2:1.0:1.0:1.0:0 */
                             0.25418297609612484);
                } else {
                  add_pred(   /* R.2:1.0:1.0:1.0:1 */
                             -0.32774939202064407);
                  if (defined_attr(1)) {  /* R.2:1.0:1.0:1.0:1.0 */
                    if (double_attr(1) <= 0.10500000000000001) {
                      add_pred(   /* R.2:1.0:1.0:1.0:1.0:0 */
                                 0.30665742750182184);
                      if (defined_attr(2)) {  /* R.2:1.0:1.0:1.0:1.0:0.0 */
                        if (double_attr(2) <= 0.475) {
                          add_pred(   /* R.2:1.0:1.0:1.0:1.0:0.0:0 */
                                     0.15860690963437762);
                        } else {
                          add_pred(   /* R.2:1.0:1.0:1.0:1.0:0.0:1 */
                                     -3.389178488345354);
                        }
                      }
                    } else {
                      add_pred(   /* R.2:1.0:1.0:1.0:1.0:1 */
                                 -0.338886957926589);
                      if (defined_attr(0)) {  /* R.2:1.0:1.0:1.0:1.0:1.0 */
                        if (double_attr(0) <= 0.315) {
                          add_pred(   /* R.2:1.0:1.0:1.0:1.0:1.0:0 */
                                     1.4398214240258587);
                        } else {
                          add_pred(   /* R.2:1.0:1.0:1.0:1.0:1.0:1 */
                                     -0.15455447408167872);
                        }
                      }
                    }
                  }
                }
              }
            }
          }
          if (defined_attr(0)) {  /* R.2:1.0:1.1 */
            if (double_attr(0) <= 0.635) {
              add_pred(   /* R.2:1.0:1.1:0 */
                         -0.1552476858952273);
              if (defined_attr(0)) {  /* R.2:1.0:1.1:0.0 */
                if (double_attr(0) <= 0.395) {
                  add_pred(   /* R.2:1.0:1.1:0.0:0 */
                             0.5845862261185172);
                } else {
                  add_pred(   /* R.2:1.0:1.1:0.0:1 */
                             -0.13511506522569336);
                  if (defined_attr(1)) {  /* R.2:1.0:1.1:0.0:1.0 */
                    if (double_attr(1) <= 0.175) {
                      add_pred(   /* R.2:1.0:1.1:0.0:1.0:0 */
                                 0.07318491266127952);
                      if (defined_attr(2)) {  /* R.2:1.0:1.1:0.0:1.0:0.0 */
                        if (double_attr(2) <= 0.20500000000000002) {
                          add_pred(   /* R.2:1.0:1.1:0.0:1.0:0.0:0 */
                                     0.2753802884965617);
                        } else {
                          add_pred(   /* R.2:1.0:1.1:0.0:1.0:0.0:1 */
                                     -0.11451398400228158);
                        }
                      }
                    } else {
                      add_pred(   /* R.2:1.0:1.1:0.0:1.0:1 */
                                 -0.739949338893404);
                      if (defined_attr(2)) {  /* R.2:1.0:1.1:0.0:1.0:1.0 */
                        if (double_attr(2) <= 0.20500000000000002) {
                          add_pred(   /* R.2:1.0:1.1:0.0:1.0:1.0:0 */
                                     0.4965869838226806);
                        } else {
                          add_pred(   /* R.2:1.0:1.1:0.0:1.0:1.0:1 */
                                     -4.073721354372835);
                        }
                      }
                      if (defined_attr(0)) {  /* R.2:1.0:1.1:0.0:1.0:1.1 */
                        if (double_attr(0) <= 0.555) {
                          add_pred(   /* R.2:1.0:1.1:0.0:1.0:1.1:0 */
                                     -3.7563824700589765);
                        } else {
                          add_pred(   /* R.2:1.0:1.1:0.0:1.0:1.1:1 */
                                     0.28538508485057723);
                        }
                      }
                    }
                  }
                }
              }
            } else {
              add_pred(   /* R.2:1.0:1.1:1 */
                         0.2893184185411965);
            }
          }
        }
      }
    }
  }

  return finalize_pred();
}

