/*************************************
This program can be used to evaluate a jboost-trained classifier on new data.  
The code contains a single procedure:

  double road_predict(void **attr, double *ret)

The first argument attr is an array of pointers corresponding to the
attributes specified in the spec file.  Thus, if attribute i is text,
then attr[i] must be a char array; if attribute i is a number, then
*attr[i] must be a double; and if attribute i is finite, then *attr[i]
must be an int containing the index of the chosen value.  An undefined
attribute is indicated by setting attr[i] to NULL.

Specifically, these pointers are:

     index    attr.type    data.type   name
   ------------------------------------------
        0     number       double      H
        1     number       double      S
        2     number       double      V

The second argument ret is a pointer to an array of k doubles, where k
is the number of classes.  The scores for each of the k classes will
be stored in this array.  If ret is NULL, then no scores are stored.
In any case, predict returns the score for class 0 (=ret[0]).

These scores correspond to the classes as follows:

            index       class name
           ------------------------
               0        0
               1        1

This classifier was automatically generated by jboost on
Thu Jun 03 19:25:23 PDT 2010.
*************************************/
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <limits.h>
#include <float.h>

typedef double Prediction_t;
#define reset_pred()  {p = 0.0;}
#define add_pred(X) {p += (X);}
#define finalize_pred()  ((r) ? (r[1] = p , r[0] = -p) : -p)
#define defined_attr(X)  (attr[X])
#define int_attr(X)      (*((int *) attr[X]))
#define attr_contains_token(X,Y) (tokens[X][Y])
#define double_attr(X)   (*((double *) attr[X]))

#define WHITE_CHARS   " \t\n"
typedef struct hash_table_entry_s {
  char *key;
  int id;
  struct hash_table_entry_s *next;
} HashTableEntry_t;
static char *keys[] = {
};
#define num_keys  (0)
static HashTableEntry_t **hash_table = NULL;
#define hash_table_size  (1031)
static char *tokens[1];
static int text_attr[] = {};
#define num_text_attr  (0)
static char **text_patterns[] = {
};

static char **words;
static int num_words;
static int cur_word;
static char *pattern;
static int pattern_len;

static void set_pattern(int n, char **m_w, char *pat) {
  words = m_w;
  pattern = pat;
  cur_word = 0;
  num_words = n;
  pattern_len = strlen(pat);
}

#define more_tokens()  (cur_word <= num_words - pattern_len)

#define ADD_CHAR(S)  { \
  if (c >= buffer_size) { \
    buffer_size = 2 * buffer_size + 1; \
    buffer = (char *) realloc(buffer, buffer_size * sizeof(char)); \
  } \
  buffer[c++] = (S); \
}

static char *next_token(void) {
  static char *buffer = NULL;
  static int buffer_size = 0;
  int i, c;
  char *s;

  c = 0;
  for (s = pattern; *s; s++)
    ADD_CHAR(*s);

  for (i = 0; i < pattern_len; i++) {
    if (pattern[i] == '1') {
      ADD_CHAR(' ');
      for (s = words[cur_word + i]; *s; s++)
	ADD_CHAR(*s);
    }
  }
  ADD_CHAR('\0');
  cur_word++;
  return buffer;
}

static int
hash(char *s) {
  static int *coef = NULL;
  static int max_len = 0;
  int len = strlen(s);
  int i, h;

  if (len > max_len) {
    i = max_len;
    max_len = 2 * len;
    coef = (int *) realloc(coef, max_len * sizeof(int));
    for (; i < max_len; i++)
      coef[i] = random() % hash_table_size;
  }

  h = 0;
  for (i = 0; i < len; i++) {
     if (h >= INT_MAX - (hash_table_size - 1) * 255)
       h = h % hash_table_size;
     h += coef[i] * s[i];
  }
  return (h % hash_table_size);
}

double road_predict(void **attr, double *r) {
  int i, j, h, a;
  HashTableEntry_t *entry;
  char *s;
  static char **words = NULL;
  static int max_word_list_size = 0;
  int num_words;
  static char *buffer = NULL;
  static int buffer_size = 0;
  char **pat;

  Prediction_t p;

  if (!hash_table) {
    hash_table = (HashTableEntry_t **)
      malloc(hash_table_size * sizeof(HashTableEntry_t *));
    for (i = 0; i < hash_table_size; i++)
      hash_table[i] = NULL;
    for (i = 0; i < num_keys; i++) {
      h = hash(keys[i]);
      entry = (HashTableEntry_t *) malloc(sizeof(HashTableEntry_t));
      entry->key = keys[i];
      entry->id = i;
      entry->next = hash_table[h];
      hash_table[h] = entry;
    }
    for (i = 0; i < num_text_attr; i++)
      tokens[text_attr[i]] = (char *) malloc(num_keys * sizeof(char));
  }

  for (i = 0; i < num_text_attr; i++) {
    a = text_attr[i];
    if (!defined_attr(a))
      continue;
    for (j = 0; j < num_keys; j++)
      tokens[a][j] = 0;

    while (strlcpy(buffer, attr[a], buffer_size) >= buffer_size) {
      buffer_size = 2 * strlen(attr[a]);
      buffer = (char *) realloc(buffer, (buffer_size+1) * sizeof(char));
    }
    num_words = 0;
    for (s = strtok(buffer, WHITE_CHARS); s; s = strtok(NULL, WHITE_CHARS)) {
      if (num_words >= max_word_list_size) {
        max_word_list_size = 2 * max_word_list_size + 1;
        words = (char **) realloc(words, max_word_list_size * sizeof(char *));
      }
      words[num_words++] = s;
    }
    for (pat = text_patterns[i]; *pat; pat++) {
      set_pattern(num_words, words, *pat);
      while (more_tokens()) {
        s = next_token();
        for (entry = hash_table[hash(s)]; entry; entry = entry->next)
          if (!strcmp(entry->key, s)) {
            tokens[a][entry->id] = 1;
            break;
          }
        }
      }
  }

  reset_pred();

  add_pred(   /* R */
             -1.597064193867718);
  if (defined_attr(2)) {  /* R.0 */
    if (double_attr(2) <= 0.46499999999999997) {
      add_pred(   /* R.0:0 */
                 0.4220546056959796);
      if (defined_attr(2)) {  /* R.0:0.0 */
        if (double_attr(2) <= 0.305) {
          add_pred(   /* R.0:0.0:0 */
                     -1.897314499221607);
          if (defined_attr(2)) {  /* R.0:0.0:0.0 */
            if (double_attr(2) <= 0.255) {
              add_pred(   /* R.0:0.0:0.0:0 */
                         -0.44071980102954017);
              if (defined_attr(2)) {  /* R.0:0.0:0.0:0.0 */
                if (double_attr(2) <= 0.0050) {
                  add_pred(   /* R.0:0.0:0.0:0.0:0 */
                             -0.7826757692395463);
                } else {
                  add_pred(   /* R.0:0.0:0.0:0.0:1 */
                             0.4025861216130376);
                }
              }
              if (defined_attr(0)) {  /* R.0:0.0:0.0:0.1 */
                if (double_attr(0) <= 0.325) {
                  add_pred(   /* R.0:0.0:0.0:0.1:0 */
                             -0.4907789064379551);
                  if (defined_attr(2)) {  /* R.0:0.0:0.0:0.1:0.0 */
                    if (double_attr(2) <= 0.235) {
                      add_pred(   /* R.0:0.0:0.0:0.1:0.0:0 */
                                 -0.1290688076929095);
                    } else {
                      add_pred(   /* R.0:0.0:0.0:0.1:0.0:1 */
                                 0.6870428265256556);
                    }
                  }
                } else {
                  add_pred(   /* R.0:0.0:0.0:0.1:1 */
                             0.688690291758867);
                  if (defined_attr(0)) {  /* R.0:0.0:0.0:0.1:1.0 */
                    if (double_attr(0) <= 0.435) {
                      add_pred(   /* R.0:0.0:0.0:0.1:1.0:0 */
                                 -0.5325139709402028);
                    } else {
                      add_pred(   /* R.0:0.0:0.0:0.1:1.0:1 */
                                 0.25141258464617067);
                    }
                  }
                }
              }
            } else {
              add_pred(   /* R.0:0.0:0.0:1 */
                         0.7553433048050209);
              if (defined_attr(2)) {  /* R.0:0.0:0.0:1.0 */
                if (double_attr(2) <= 0.28500000000000003) {
                  add_pred(   /* R.0:0.0:0.0:1.0:0 */
                             0.04071787400148776);
                } else {
                  add_pred(   /* R.0:0.0:0.0:1.0:1 */
                             0.3414890588855654);
                }
              }
            }
          }
        } else {
          add_pred(   /* R.0:0.0:1 */
                     0.5697069189347067);
          if (defined_attr(1)) {  /* R.0:0.0:1.0 */
            if (double_attr(1) <= 0.185) {
              add_pred(   /* R.0:0.0:1.0:0 */
                         0.10022385417575264);
              if (defined_attr(1)) {  /* R.0:0.0:1.0:0.0 */
                if (double_attr(1) <= 0.155) {
                  add_pred(   /* R.0:0.0:1.0:0.0:0 */
                             0.007349714973745437);
                } else {
                  add_pred(   /* R.0:0.0:1.0:0.0:1 */
                             -0.40719557505927295);
                }
              }
            } else {
              add_pred(   /* R.0:0.0:1.0:1 */
                         -2.230145391295651);
              if (defined_attr(1)) {  /* R.0:0.0:1.0:1.0 */
                if (double_attr(1) <= 0.28500000000000003) {
                  add_pred(   /* R.0:0.0:1.0:1.0:0 */
                             0.6884957147589397);
                } else {
                  add_pred(   /* R.0:0.0:1.0:1.0:1 */
                             -3.3979817050668624);
                }
              }
            }
          }
          if (defined_attr(2)) {  /* R.0:0.0:1.1 */
            if (double_attr(2) <= 0.325) {
              add_pred(   /* R.0:0.0:1.1:0 */
                         -0.5065086749541781);
            } else {
              add_pred(   /* R.0:0.0:1.1:1 */
                         0.006227780835538323);
            }
          }
        }
      }
      if (defined_attr(2)) {  /* R.0:0.1 */
        if (double_attr(2) <= 0.435) {
          add_pred(   /* R.0:0.1:0 */
                     0.16067403601294608);
          if (defined_attr(1)) {  /* R.0:0.1:0.0 */
            if (double_attr(1) <= 0.10500000000000001) {
              add_pred(   /* R.0:0.1:0.0:0 */
                         0.036425530140898554);
            } else {
              add_pred(   /* R.0:0.1:0.0:1 */
                         -0.2719987452187639);
              if (defined_attr(2)) {  /* R.0:0.1:0.0:1.0 */
                if (double_attr(2) <= 0.065) {
                  add_pred(   /* R.0:0.1:0.0:1.0:0 */
                             1.0539668489347602);
                } else {
                  add_pred(   /* R.0:0.1:0.0:1.0:1 */
                             -0.1766029358702723);
                  if (defined_attr(0)) {  /* R.0:0.1:0.0:1.0:1.0 */
                    if (double_attr(0) <= 0.445) {
                      add_pred(   /* R.0:0.1:0.0:1.0:1.0:0 */
                                 -3.449699288259025E-4);
                      if (defined_attr(1)) {  /* R.0:0.1:0.0:1.0:1.0:0.0 */
                        if (double_attr(1) <= 0.345) {
                          add_pred(   /* R.0:0.1:0.0:1.0:1.0:0.0:0 */
                                     0.04116218853086249);
                        } else {
                          add_pred(   /* R.0:0.1:0.0:1.0:1.0:0.0:1 */
                                     -3.5318756337848027);
                        }
                      }
                    } else {
                      add_pred(   /* R.0:0.1:0.0:1.0:1.0:1 */
                                 -4.081815501578987);
                    }
                  }
                }
              }
            }
          }
        } else {
          add_pred(   /* R.0:0.1:1 */
                     -0.7375587161412879);
          if (defined_attr(2)) {  /* R.0:0.1:1.0 */
            if (double_attr(2) <= 0.455) {
              add_pred(   /* R.0:0.1:1.0:0 */
                         0.16301948759419216);
              if (defined_attr(2)) {  /* R.0:0.1:1.0:0.0 */
                if (double_attr(2) <= 0.445) {
                  add_pred(   /* R.0:0.1:1.0:0.0:0 */
                             0.2572742190994848);
                } else {
                  add_pred(   /* R.0:0.1:1.0:0.0:1 */
                             -0.16473384825723364);
                }
              }
            } else {
              add_pred(   /* R.0:0.1:1.0:1 */
                         -0.6392909010285918);
            }
          }
        }
      }
    } else {
      add_pred(   /* R.0:1 */
                 -0.9552119202426708);
      if (defined_attr(1)) {  /* R.0:1.0 */
        if (double_attr(1) <= 0.10500000000000001) {
          add_pred(   /* R.0:1.0:0 */
                     -0.22681511753299208);
          if (defined_attr(1)) {  /* R.0:1.0:0.0 */
            if (double_attr(1) <= 0.095) {
              add_pred(   /* R.0:1.0:0.0:0 */
                         -0.03123456889964638);
            } else {
              add_pred(   /* R.0:1.0:0.0:1 */
                         0.7574221534697834);
              if (defined_attr(0)) {  /* R.0:1.0:0.0:1.0 */
                if (double_attr(0) <= 0.135) {
                  add_pred(   /* R.0:1.0:0.0:1.0:0 */
                             -3.662104993468083);
                } else {
                  add_pred(   /* R.0:1.0:0.0:1.0:1 */
                             0.217907075879262);
                }
              }
              if (defined_attr(2)) {  /* R.0:1.0:0.0:1.1 */
                if (double_attr(2) <= 0.525) {
                  add_pred(   /* R.0:1.0:0.0:1.1:0 */
                             -0.5783869273322154);
                } else {
                  add_pred(   /* R.0:1.0:0.0:1.1:1 */
                             0.19081546311041797);
                }
              }
            }
          }
        } else {
          add_pred(   /* R.0:1.0:1 */
                     0.5465977899122572);
          if (defined_attr(0)) {  /* R.0:1.0:1.0 */
            if (double_attr(0) <= 0.175) {
              add_pred(   /* R.0:1.0:1.0:0 */
                         -0.42268729299705615);
            } else {
              add_pred(   /* R.0:1.0:1.0:1 */
                         0.7497241680186989);
              if (defined_attr(2)) {  /* R.0:1.0:1.0:1.0 */
                if (double_attr(2) <= 0.705) {
                  add_pred(   /* R.0:1.0:1.0:1.0:0 */
                             -0.06454841134151412);
                } else {
                  add_pred(   /* R.0:1.0:1.0:1.0:1 */
                             -1.961325652809376);
                }
              }
            }
          }
        }
      }
      if (defined_attr(2)) {  /* R.0:1.1 */
        if (double_attr(2) <= 0.925) {
          add_pred(   /* R.0:1.1:0 */
                     0.02962713287587681);
          if (defined_attr(1)) {  /* R.0:1.1:0.0 */
            if (double_attr(1) <= 0.215) {
              add_pred(   /* R.0:1.1:0.0:0 */
                         0.11442455570008606);
            } else {
              add_pred(   /* R.0:1.1:0.0:1 */
                         -4.283966217054164);
            }
          }
          if (defined_attr(1)) {  /* R.0:1.1:0.1 */
            if (double_attr(1) <= 0.025) {
              add_pred(   /* R.0:1.1:0.1:0 */
                         0.18061190217139547);
              if (defined_attr(2)) {  /* R.0:1.1:0.1:0.0 */
                if (double_attr(2) <= 0.755) {
                  add_pred(   /* R.0:1.1:0.1:0.0:0 */
                             0.2544098238179684);
                } else {
                  add_pred(   /* R.0:1.1:0.1:0.0:1 */
                             -0.19202556004756147);
                }
              }
            } else {
              add_pred(   /* R.0:1.1:0.1:1 */
                         -0.13613717079190457);
              if (defined_attr(0)) {  /* R.0:1.1:0.1:1.0 */
                if (double_attr(0) <= 0.535) {
                  add_pred(   /* R.0:1.1:0.1:1.0:0 */
                             -0.007786960687892926);
                  if (defined_attr(0)) {  /* R.0:1.1:0.1:1.0:0.0 */
                    if (double_attr(0) <= 0.20500000000000002) {
                      add_pred(   /* R.0:1.1:0.1:1.0:0.0:0 */
                                 -0.039177851387619554);
                      if (defined_attr(1)) {  /* R.0:1.1:0.1:1.0:0.0:0.0 */
                        if (double_attr(1) <= 0.07500000000000001) {
                          add_pred(   /* R.0:1.1:0.1:1.0:0.0:0.0:0 */
                                     -0.13827694795559928);
                        } else {
                          add_pred(   /* R.0:1.1:0.1:1.0:0.0:0.0:1 */
                                     0.07012692628615218);
                        }
                      }
                    } else {
                      add_pred(   /* R.0:1.1:0.1:1.0:0.0:1 */
                                 0.24650983522845607);
                    }
                  }
                  if (defined_attr(0)) {  /* R.0:1.1:0.1:1.0:0.1 */
                    if (double_attr(0) <= 0.07500000000000001) {
                      add_pred(   /* R.0:1.1:0.1:1.0:0.1:0 */
                                 -3.385878962196831);
                    } else {
                      add_pred(   /* R.0:1.1:0.1:1.0:0.1:1 */
                                 0.03511140981766193);
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.1:0.1:1.0:1 */
                             -4.214318111647484);
                }
              }
            }
          }
        } else {
          add_pred(   /* R.0:1.1:1 */
                     -0.8687793536171372);
          if (defined_attr(2)) {  /* R.0:1.1:1.0 */
            if (double_attr(2) <= 0.985) {
              add_pred(   /* R.0:1.1:1.0:0 */
                         0.46941989990789273);
            } else {
              add_pred(   /* R.0:1.1:1.0:1 */
                         -0.13169942178410535);
            }
          }
        }
      }
    }
  }
  if (defined_attr(1)) {  /* R.1 */
    if (double_attr(1) <= 0.055) {
      add_pred(   /* R.1:0 */
                 0.5853292422630484);
      if (defined_attr(1)) {  /* R.1:0.0 */
        if (double_attr(1) <= 0.035) {
          add_pred(   /* R.1:0.0:0 */
                     0.17818954653330452);
          if (defined_attr(1)) {  /* R.1:0.0:0.0 */
            if (double_attr(1) <= 0.025) {
              add_pred(   /* R.1:0.0:0.0:0 */
                         0.0255117518207609);
              if (defined_attr(2)) {  /* R.1:0.0:0.0:0.0 */
                if (double_attr(2) <= 0.405) {
                  add_pred(   /* R.1:0.0:0.0:0.0:0 */
                             0.08060349580850648);
                } else {
                  add_pred(   /* R.1:0.0:0.0:0.0:1 */
                             -0.06634636759763834);
                }
              }
            } else {
              add_pred(   /* R.1:0.0:0.0:1 */
                         -0.14122319690015067);
              if (defined_attr(2)) {  /* R.1:0.0:0.0:1.0 */
                if (double_attr(2) <= 0.245) {
                  add_pred(   /* R.1:0.0:0.0:1.0:0 */
                             -3.556418947202984);
                } else {
                  add_pred(   /* R.1:0.0:0.0:1.0:1 */
                             -0.058437808601486056);
                }
              }
            }
          }
        } else {
          add_pred(   /* R.1:0.0:1 */
                     -0.45325032443055197);
          if (defined_attr(1)) {  /* R.1:0.0:1.0 */
            if (double_attr(1) <= 0.045) {
              add_pred(   /* R.1:0.0:1.0:0 */
                         0.08413501929690906);
            } else {
              add_pred(   /* R.1:0.0:1.0:1 */
                         -0.12061949782385079);
              if (defined_attr(2)) {  /* R.1:0.0:1.0:1.0 */
                if (double_attr(2) <= 0.445) {
                  add_pred(   /* R.1:0.0:1.0:1.0:0 */
                             0.0787728669557803);
                } else {
                  add_pred(   /* R.1:0.0:1.0:1.0:1 */
                             -0.29123677866882197);
                }
              }
            }
          }
        }
      }
      if (defined_attr(2)) {  /* R.1:0.1 */
        if (double_attr(2) <= 0.385) {
          add_pred(   /* R.1:0.1:0 */
                     0.08736024854182724);
          if (defined_attr(2)) {  /* R.1:0.1:0.0 */
            if (double_attr(2) <= 0.355) {
              add_pred(   /* R.1:0.1:0.0:0 */
                         -0.09059036117198349);
            } else {
              add_pred(   /* R.1:0.1:0.0:1 */
                         0.11445953947725418);
            }
          }
        } else {
          add_pred(   /* R.1:0.1:1 */
                     -0.1212826529839935);
          if (defined_attr(1)) {  /* R.1:0.1:1.0 */
            if (double_attr(1) <= 0.015) {
              add_pred(   /* R.1:0.1:1.0:0 */
                         0.15368210161135717);
            } else {
              add_pred(   /* R.1:0.1:1.0:1 */
                         -0.07904250665717148);
              if (defined_attr(0)) {  /* R.1:0.1:1.0:1.0 */
                if (double_attr(0) <= 0.375) {
                  add_pred(   /* R.1:0.1:1.0:1.0:0 */
                             0.06150090757251084);
                  if (defined_attr(2)) {  /* R.1:0.1:1.0:1.0:0.0 */
                    if (double_attr(2) <= 0.945) {
                      add_pred(   /* R.1:0.1:1.0:1.0:0.0:0 */
                                 0.01768252432264775);
                    } else {
                      add_pred(   /* R.1:0.1:1.0:1.0:0.0:1 */
                                 0.47387329961708485);
                    }
                  }
                } else {
                  add_pred(   /* R.1:0.1:1.0:1.0:1 */
                             -0.16277560292325188);
                  if (defined_attr(2)) {  /* R.1:0.1:1.0:1.0:1.0 */
                    if (double_attr(2) <= 0.715) {
                      add_pred(   /* R.1:0.1:1.0:1.0:1.0:0 */
                                 0.06500078065866514);
                    } else {
                      add_pred(   /* R.1:0.1:1.0:1.0:1.0:1 */
                                 -0.8950610318083009);
                    }
                  }
                  if (defined_attr(1)) {  /* R.1:0.1:1.0:1.0:1.1 */
                    if (double_attr(1) <= 0.035) {
                      add_pred(   /* R.1:0.1:1.0:1.0:1.1:0 */
                                 0.03319926385578571);
                    } else {
                      add_pred(   /* R.1:0.1:1.0:1.0:1.1:1 */
                                 -0.2706396006161499);
                    }
                  }
                }
              }
            }
          }
        }
      }
    } else {
      add_pred(   /* R.1:1 */
                 -0.5711909886570999);
      if (defined_attr(0)) {  /* R.1:1.0 */
        if (double_attr(0) <= 0.375) {
          add_pred(   /* R.1:1.0:0 */
                     0.09596540017972685);
        } else {
          add_pred(   /* R.1:1.0:1 */
                     -0.4799499005708399);
          if (defined_attr(1)) {  /* R.1:1.0:1.0 */
            if (double_attr(1) <= 0.07500000000000001) {
              add_pred(   /* R.1:1.0:1.0:0 */
                         0.320783001036651);
            } else {
              add_pred(   /* R.1:1.0:1.0:1 */
                         -0.7471290155329205);
              if (defined_attr(2)) {  /* R.1:1.0:1.0:1.0 */
                if (double_attr(2) <= 0.305) {
                  add_pred(   /* R.1:1.0:1.0:1.0:0 */
                             0.38548951416753663);
                } else {
                  add_pred(   /* R.1:1.0:1.0:1.0:1 */
                             -0.30877398287625957);
                  if (defined_attr(1)) {  /* R.1:1.0:1.0:1.0:1.0 */
                    if (double_attr(1) <= 0.08499999999999999) {
                      add_pred(   /* R.1:1.0:1.0:1.0:1.0:0 */
                                 0.6752302262758052);
                    } else {
                      add_pred(   /* R.1:1.0:1.0:1.0:1.0:1 */
                                 -0.6090250324769724);
                    }
                  }
                }
              }
            }
          }
          if (defined_attr(2)) {  /* R.1:1.0:1.1 */
            if (double_attr(2) <= 0.385) {
              add_pred(   /* R.1:1.0:1.1:0 */
                         0.17096247860341565);
            } else {
              add_pred(   /* R.1:1.0:1.1:1 */
                         -1.026203463735045);
              if (defined_attr(0)) {  /* R.1:1.0:1.1:1.0 */
                if (double_attr(0) <= 0.505) {
                  add_pred(   /* R.1:1.0:1.1:1.0:0 */
                             0.2596533643002839);
                } else {
                  add_pred(   /* R.1:1.0:1.1:1.0:1 */
                             -3.716317896678761);
                }
              }
              if (defined_attr(2)) {  /* R.1:1.0:1.1:1.1 */
                if (double_attr(2) <= 0.455) {
                  add_pred(   /* R.1:1.0:1.1:1.1:0 */
                             0.14351900335044607);
                } else {
                  add_pred(   /* R.1:1.0:1.1:1.1:1 */
                             -3.5784823291699692);
                }
              }
            }
          }
        }
      }
      if (defined_attr(2)) {  /* R.1:1.1 */
        if (double_attr(2) <= 0.765) {
          add_pred(   /* R.1:1.1:0 */
                     0.1020604912141886);
          if (defined_attr(0)) {  /* R.1:1.1:0.0 */
            if (double_attr(0) <= 0.065) {
              add_pred(   /* R.1:1.1:0.0:0 */
                         -1.7717338595580363);
            } else {
              add_pred(   /* R.1:1.1:0.0:1 */
                         0.1152125407070975);
            }
          }
          if (defined_attr(0)) {  /* R.1:1.1:0.1 */
            if (double_attr(0) <= 0.675) {
              add_pred(   /* R.1:1.1:0.1:0 */
                         0.02403950285181621);
              if (defined_attr(0)) {  /* R.1:1.1:0.1:0.0 */
                if (double_attr(0) <= 0.665) {
                  add_pred(   /* R.1:1.1:0.1:0.0:0 */
                             0.020059653563011558);
                } else {
                  add_pred(   /* R.1:1.1:0.1:0.0:1 */
                             1.1531815048898952);
                }
              }
            } else {
              add_pred(   /* R.1:1.1:0.1:1 */
                         -1.5719133537986651);
            }
          }
        } else {
          add_pred(   /* R.1:1.1:1 */
                     -4.235244151656126);
        }
      }
    }
  }
  if (defined_attr(0)) {  /* R.2 */
    if (double_attr(0) <= 0.46499999999999997) {
      add_pred(   /* R.2:0 */
                 0.1770322454007074);
      if (defined_attr(0)) {  /* R.2:0.0 */
        if (double_attr(0) <= 0.14500000000000002) {
          add_pred(   /* R.2:0.0:0 */
                     -0.9559487319949828);
          if (defined_attr(1)) {  /* R.2:0.0:0.0 */
            if (double_attr(1) <= 0.015) {
              add_pred(   /* R.2:0.0:0.0:0 */
                         0.5186952636616904);
            } else {
              add_pred(   /* R.2:0.0:0.0:1 */
                         -0.13400171448814163);
              if (defined_attr(2)) {  /* R.2:0.0:0.0:1.0 */
                if (double_attr(2) <= 0.495) {
                  add_pred(   /* R.2:0.0:0.0:1.0:0 */
                             0.2991271326128373);
                } else {
                  add_pred(   /* R.2:0.0:0.0:1.0:1 */
                             -0.39957806240773575);
                  if (defined_attr(1)) {  /* R.2:0.0:0.0:1.0:1.0 */
                    if (double_attr(1) <= 0.125) {
                      add_pred(   /* R.2:0.0:0.0:1.0:1.0:0 */
                                 -0.35100818743973544);
                      if (defined_attr(2)) {  /* R.2:0.0:0.0:1.0:1.0:0.0 */
                        if (double_attr(2) <= 0.575) {
                          add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.0:0 */
                                     -0.787329343314925);
                          if (defined_attr(1)) {  /* R.2:0.0:0.0:1.0:1.0:0.0:0.0 */
                            if (double_attr(1) <= 0.025) {
                              add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.0:0.0:0 */
                                         0.6795251364386453);
                              if (defined_attr(2)) {  /* R.2:0.0:0.0:1.0:1.0:0.0:0.0:0.0 */
                                if (double_attr(2) <= 0.525) {
                                  add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.0:0.0:0.0:0 */
                                             -3.3265881644843533);
                                } else {
                                  add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.0:0.0:0.0:1 */
                                             0.4484629598786594);
                                }
                              }
                            } else {
                              add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.0:0.0:1 */
                                         -0.1670739193057502);
                              if (defined_attr(0)) {  /* R.2:0.0:0.0:1.0:1.0:0.0:0.0:1.0 */
                                if (double_attr(0) <= 0.135) {
                                  add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.0:0.0:1.0:0 */
                                             -3.844503642116834);
                                } else {
                                  add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.0:0.0:1.0:1 */
                                             0.3081459827255808);
                                }
                              }
                            }
                          }
                        } else {
                          add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.0:1 */
                                     0.6062594787370843);
                        }
                      }
                      if (defined_attr(1)) {  /* R.2:0.0:0.0:1.0:1.0:0.1 */
                        if (double_attr(1) <= 0.055) {
                          add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.1:0 */
                                     0.3075988171624947);
                        } else {
                          add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.1:1 */
                                     -0.5264965579848656);
                          if (defined_attr(1)) {  /* R.2:0.0:0.0:1.0:1.0:0.1:1.0 */
                            if (double_attr(1) <= 0.10500000000000001) {
                              add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.1:1.0:0 */
                                         -1.120789738891589);
                              if (defined_attr(2)) {  /* R.2:0.0:0.0:1.0:1.0:0.1:1.0:0.0 */
                                if (double_attr(2) <= 0.575) {
                                  add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.1:1.0:0.0:0 */
                                             -3.9247283386096057);
                                } else {
                                  add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.1:1.0:0.0:1 */
                                             -0.0010616314065481534);
                                }
                              }
                            } else {
                              add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.1:1.0:1 */
                                         0.5879133509634654);
                              if (defined_attr(0)) {  /* R.2:0.0:0.0:1.0:1.0:0.1:1.0:1.0 */
                                if (double_attr(0) <= 0.11499999999999999) {
                                  add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.1:1.0:1.0:0 */
                                             -3.992931522490655);
                                } else {
                                  add_pred(   /* R.2:0.0:0.0:1.0:1.0:0.1:1.0:1.0:1 */
                                             0.30407479599668075);
                                }
                              }
                            }
                          }
                        }
                      }
                    } else {
                      add_pred(   /* R.2:0.0:0.0:1.0:1.0:1 */
                                 0.653500663420442);
                    }
                  }
                  if (defined_attr(0)) {  /* R.2:0.0:0.0:1.0:1.1 */
                    if (double_attr(0) <= 0.10500000000000001) {
                      add_pred(   /* R.2:0.0:0.0:1.0:1.1:0 */
                                 -0.9582475229199795);
                      if (defined_attr(2)) {  /* R.2:0.0:0.0:1.0:1.1:0.0 */
                        if (double_attr(2) <= 0.995) {
                          add_pred(   /* R.2:0.0:0.0:1.0:1.1:0.0:0 */
                                     -0.27749183211082695);
                          if (defined_attr(1)) {  /* R.2:0.0:0.0:1.0:1.1:0.0:0.0 */
                            if (double_attr(1) <= 0.135) {
                              add_pred(   /* R.2:0.0:0.0:1.0:1.1:0.0:0.0:0 */
                                         -4.02342448544197);
                            } else {
                              add_pred(   /* R.2:0.0:0.0:1.0:1.1:0.0:0.0:1 */
                                         0.5294677831416517);
                            }
                          }
                        } else {
                          add_pred(   /* R.2:0.0:0.0:1.0:1.1:0.0:1 */
                                     2.7425836194295807);
                        }
                      }
                    } else {
                      add_pred(   /* R.2:0.0:0.0:1.0:1.1:1 */
                                 0.295396584220695);
                      if (defined_attr(2)) {  /* R.2:0.0:0.0:1.0:1.1:1.0 */
                        if (double_attr(2) <= 0.845) {
                          add_pred(   /* R.2:0.0:0.0:1.0:1.1:1.0:0 */
                                     0.0012231069518239702);
                        } else {
                          add_pred(   /* R.2:0.0:0.0:1.0:1.1:1.0:1 */
                                     -3.47358515478411);
                        }
                      }
                    }
                  }
                }
              }
              if (defined_attr(0)) {  /* R.2:0.0:0.0:1.1 */
                if (double_attr(0) <= 0.135) {
                  add_pred(   /* R.2:0.0:0.0:1.1:0 */
                             -0.1614034637911558);
                  if (defined_attr(1)) {  /* R.2:0.0:0.0:1.1:0.0 */
                    if (double_attr(1) <= 0.135) {
                      add_pred(   /* R.2:0.0:0.0:1.1:0.0:0 */
                                 -0.08956911291894257);
                      if (defined_attr(0)) {  /* R.2:0.0:0.0:1.1:0.0:0.0 */
                        if (double_attr(0) <= 0.11499999999999999) {
                          add_pred(   /* R.2:0.0:0.0:1.1:0.0:0.0:0 */
                                     -0.14909650650670916);
                        } else {
                          add_pred(   /* R.2:0.0:0.0:1.1:0.0:0.0:1 */
                                     0.21743320333373417);
                        }
                      }
                    } else {
                      add_pred(   /* R.2:0.0:0.0:1.1:0.0:1 */
                                 0.37939458887819677);
                      if (defined_attr(2)) {  /* R.2:0.0:0.0:1.1:0.0:1.0 */
                        if (double_attr(2) <= 0.355) {
                          add_pred(   /* R.2:0.0:0.0:1.1:0.0:1.0:0 */
                                     -1.7071173818379157);
                        } else {
                          add_pred(   /* R.2:0.0:0.0:1.1:0.0:1.0:1 */
                                     0.1517039267897933);
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.2:0.0:0.0:1.1:1 */
                             0.3163401813111463);
                  if (defined_attr(2)) {  /* R.2:0.0:0.0:1.1:1.0 */
                    if (double_attr(2) <= 0.10500000000000001) {
                      add_pred(   /* R.2:0.0:0.0:1.1:1.0:0 */
                                 2.2847473074211186);
                    } else {
                      add_pred(   /* R.2:0.0:0.0:1.1:1.0:1 */
                                 0.07727638783197806);
                      if (defined_attr(1)) {  /* R.2:0.0:0.0:1.1:1.0:1.0 */
                        if (double_attr(1) <= 0.195) {
                          add_pred(   /* R.2:0.0:0.0:1.1:1.0:1.0:0 */
                                     0.057588849547312575);
                        } else {
                          add_pred(   /* R.2:0.0:0.0:1.1:1.0:1.0:1 */
                                     -3.9545313534868027);
                        }
                      }
                      if (defined_attr(1)) {  /* R.2:0.0:0.0:1.1:1.0:1.1 */
                        if (double_attr(1) <= 0.165) {
                          add_pred(   /* R.2:0.0:0.0:1.1:1.0:1.1:0 */
                                     0.004380258816474988);
                        } else {
                          add_pred(   /* R.2:0.0:0.0:1.1:1.0:1.1:1 */
                                     -0.8479894075936587);
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        } else {
          add_pred(   /* R.2:0.0:1 */
                     0.3978062899394239);
          if (defined_attr(0)) {  /* R.2:0.0:1.0 */
            if (double_attr(0) <= 0.185) {
              add_pred(   /* R.2:0.0:1.0:0 */
                         -0.305382477079848);
              if (defined_attr(1)) {  /* R.2:0.0:1.0:0.0 */
                if (double_attr(1) <= 0.245) {
                  add_pred(   /* R.2:0.0:1.0:0.0:0 */
                             -0.12547812731097324);
                } else {
                  add_pred(   /* R.2:0.0:1.0:0.0:1 */
                             0.7164889081916559);
                }
              }
              if (defined_attr(2)) {  /* R.2:0.0:1.0:0.1 */
                if (double_attr(2) <= 0.575) {
                  add_pred(   /* R.2:0.0:1.0:0.1:0 */
                             -0.10887963085307951);
                  if (defined_attr(2)) {  /* R.2:0.0:1.0:0.1:0.0 */
                    if (double_attr(2) <= 0.515) {
                      add_pred(   /* R.2:0.0:1.0:0.1:0.0:0 */
                                 0.02030958959233728);
                    } else {
                      add_pred(   /* R.2:0.0:1.0:0.1:0.0:1 */
                                 -0.2691275146349069);
                    }
                  }
                } else {
                  add_pred(   /* R.2:0.0:1.0:0.1:1 */
                             0.1180921860611614);
                }
              }
            } else {
              add_pred(   /* R.2:0.0:1.0:1 */
                         0.030741413892743985);
              if (defined_attr(0)) {  /* R.2:0.0:1.0:1.0 */
                if (double_attr(0) <= 0.28500000000000003) {
                  add_pred(   /* R.2:0.0:1.0:1.0:0 */
                             0.07043768389296742);
                  if (defined_attr(1)) {  /* R.2:0.0:1.0:1.0:0.0 */
                    if (double_attr(1) <= 0.165) {
                      add_pred(   /* R.2:0.0:1.0:1.0:0.0:0 */
                                 0.0377749496219038);
                    } else {
                      add_pred(   /* R.2:0.0:1.0:1.0:0.0:1 */
                                 -0.4799658395749481);
                      if (defined_attr(2)) {  /* R.2:0.0:1.0:1.0:0.0:1.0 */
                        if (double_attr(2) <= 0.255) {
                          add_pred(   /* R.2:0.0:1.0:1.0:0.0:1.0:0 */
                                     -4.091179837976843);
                        } else {
                          add_pred(   /* R.2:0.0:1.0:1.0:0.0:1.0:1 */
                                     0.16986108502494215);
                        }
                      }
                      if (defined_attr(2)) {  /* R.2:0.0:1.0:1.0:0.0:1.1 */
                        if (double_attr(2) <= 0.345) {
                          add_pred(   /* R.2:0.0:1.0:1.0:0.0:1.1:0 */
                                     -0.3367429481620074);
                        } else {
                          add_pred(   /* R.2:0.0:1.0:1.0:0.0:1.1:1 */
                                     0.5338230410141139);
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.2:0.0:1.0:1.0:1 */
                             -0.18972359305271094);
                  if (defined_attr(2)) {  /* R.2:0.0:1.0:1.0:1.0 */
                    if (double_attr(2) <= 0.995) {
                      add_pred(   /* R.2:0.0:1.0:1.0:1.0:0 */
                                 -0.00574964606601492);
                      if (defined_attr(1)) {  /* R.2:0.0:1.0:1.0:1.0:0.0 */
                        if (double_attr(1) <= 0.065) {
                          add_pred(   /* R.2:0.0:1.0:1.0:1.0:0.0:0 */
                                     0.030791536723662017);
                        } else {
                          add_pred(   /* R.2:0.0:1.0:1.0:1.0:0.0:1 */
                                     -0.3116474875903078);
                        }
                      }
                    } else {
                      add_pred(   /* R.2:0.0:1.0:1.0:1.0:1 */
                                 -3.9113764266603592);
                    }
                  }
                }
              }
            }
          }
        }
      }
    } else {
      add_pred(   /* R.2:1 */
                 -1.2168661073466367);
      if (defined_attr(1)) {  /* R.2:1.0 */
        if (double_attr(1) <= 0.135) {
          add_pred(   /* R.2:1.0:0 */
                     0.20041000097697098);
          if (defined_attr(0)) {  /* R.2:1.0:0.0 */
            if (double_attr(0) <= 0.615) {
              add_pred(   /* R.2:1.0:0.0:0 */
                         0.24942867172486238);
              if (defined_attr(2)) {  /* R.2:1.0:0.0:0.0 */
                if (double_attr(2) <= 0.835) {
                  add_pred(   /* R.2:1.0:0.0:0.0:0 */
                             0.06107349569461628);
                } else {
                  add_pred(   /* R.2:1.0:0.0:0.0:1 */
                             -4.216130697899038);
                }
              }
              if (defined_attr(0)) {  /* R.2:1.0:0.0:0.1 */
                if (double_attr(0) <= 0.605) {
                  add_pred(   /* R.2:1.0:0.0:0.1:0 */
                             -0.24010121936770384);
                } else {
                  add_pred(   /* R.2:1.0:0.0:0.1:1 */
                             0.27594889655648724);
                }
              }
            } else {
              add_pred(   /* R.2:1.0:0.0:1 */
                         -0.15395389498763956);
            }
          }
        } else {
          add_pred(   /* R.2:1.0:1 */
                     -5.042885499690481);
        }
      }
    }
  }
  if (defined_attr(1)) {  /* R.3 */
    if (double_attr(1) <= 0.245) {
      add_pred(   /* R.3:0 */
                 0.017707314615550675);
      if (defined_attr(1)) {  /* R.3:0.0 */
        if (double_attr(1) <= 0.20500000000000002) {
          add_pred(   /* R.3:0.0:0 */
                     0.005667912718649669);
        } else {
          add_pred(   /* R.3:0.0:1 */
                     -0.5303326382605167);
        }
      }
    } else {
      add_pred(   /* R.3:1 */
                 -1.1155038881937027);
      if (defined_attr(2)) {  /* R.3:1.0 */
        if (double_attr(2) <= 0.365) {
          add_pred(   /* R.3:1.0:0 */
                     0.2258156946296637);
        } else {
          add_pred(   /* R.3:1.0:1 */
                     -3.4439596676112036);
        }
      }
    }
  }

  return finalize_pred();
}

