exampleTerminator=;
attributeTerminator=,
maxBadExa=0
word_freq_make         number
word_freq_address      number
word_freq_all          number
word_freq_3d           number
word_freq_our          number
word_freq_over         number
word_freq_remove       number
word_freq_internet     number
word_freq_order        number
word_freq_mail         number
word_freq_receive      number
word_freq_will         number
word_freq_people       number
word_freq_report       number
word_freq_addresses    number
word_freq_free         number
word_freq_business     number
word_freq_email        number
word_freq_you          number
word_freq_credit       number
word_freq_your         number
word_freq_font         number
word_freq_000          number
word_freq_money        number
word_freq_hp           number
word_freq_hpl          number
word_freq_george       number
word_freq_650          number
word_freq_lab          number
word_freq_labs         number
word_freq_telnet       number
word_freq_857          number
word_freq_data         number
word_freq_415          number
word_freq_85           number
word_freq_technology   number
word_freq_1999         number
word_freq_parts        number
word_freq_pm           number
word_freq_direct       number
word_freq_cs           number
word_freq_meeting      number
word_freq_original     number
word_freq_project      number
word_freq_re           number
word_freq_edu          number
word_freq_table        number
word_freq_conference   number
char_freq_semi         number
char_freq_paren        number
char_freq_bracket      number
char_freq_bang         number
char_freq_dollar       number
char_freq_hash         number
capital_run_length_average number
capital_run_length_longest number
capital_run_length_total   number
labels (+1,-1)
