% This function evaluates a jboost-trained classifier.  The first 
% argument is an array of values corresponding to the formatted data
% used during training.  The second argument is an array of values
% indicating which of the attributes are defined (where non-zero means
% that the corresponding attribute is defined).
% This classifier was automatically generated by jboost on:
% Wed May 12 14:08:00 PDT 2010
function pred = predict(val, def)
  pred = zeros([1,1]);
  pred = pred + [   % R
             2.8713391216310353E-4];
  if def(1) % R.0
    if val(1) <= 0.245
      pred = pred + [   % R.0:0
                 -0.8554763728055909];
      if def(3) % R.0:0.0
        if val(3) <= 0.605
          pred = pred + [   % R.0:0.0:0
                     -0.4577711632934452];
          if def(3) % R.0:0.0:0.0
            if val(3) <= 0.505
              pred = pred + [   % R.0:0.0:0.0:0
                         0.7324677748441651];
              if def(3) % R.0:0.0:0.0:0.0
                if val(3) <= 0.0050
                  pred = pred + [   % R.0:0.0:0.0:0.0:0
                             -2.446680696318241];
                else
                  pred = pred + [   % R.0:0.0:0.0:0.0:1
                             0.5115397768988639];
                end
              end
            else
              pred = pred + [   % R.0:0.0:0.0:1
                         -0.4925746903910935];
              if def(2) % R.0:0.0:0.0:1.0
                if val(2) <= 0.045
                  pred = pred + [   % R.0:0.0:0.0:1.0:0
                             1.019598860536937];
                else
                  pred = pred + [   % R.0:0.0:0.0:1.0:1
                             -0.26206807063524495];
                end
              end
            end
          end
        else
          pred = pred + [   % R.0:0.0:1
                     1.2004282929171979];
          if def(2) % R.0:0.0:1.0
            if val(2) <= 0.015
              pred = pred + [   % R.0:0.0:1.0:0
                         0.24858270273478134];
            else
              pred = pred + [   % R.0:0.0:1.0:1
                         -0.5237489871439669];
            end
          end
        end
      end
    else
      pred = pred + [   % R.0:1
                 0.7869410259910231];
      if def(3) % R.0:1.0
        if val(3) <= 0.035
          pred = pred + [   % R.0:1.0:0
                     -2.1368375388489596];
        else
          pred = pred + [   % R.0:1.0:1
                     -0.002467387327790431];
        end
      end
    end
  end
  if def(3) % R.1
    if val(3) <= 0.985
      pred = pred + [   % R.1:0
                 -0.06565544557527368];
      if def(2) % R.1:0.0
        if val(2) <= 0.135
          pred = pred + [   % R.1:0.0:0
                     -0.1623234925147344];
        else
          pred = pred + [   % R.1:0.0:1
                     0.3529786178523373];
        end
      end
    else
      pred = pred + [   % R.1:1
                 1.2000592917371895];
    end
  end
  if def(1) % R.2
    if val(1) <= 0.615
      pred = pred + [   % R.2:0
                 0.09715211353067084];
    else
      pred = pred + [   % R.2:1
                 -0.23617306072711874];
    end
  end


